//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.SystemConfig {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtAfterDays;
		protected global::System.Web.UI.WebControls.TextBox txtTimingDays;
		protected global::System.Web.UI.WebControls.TextBox txtAccount;
		protected global::System.Web.UI.WebControls.TextBox txtLogPath;
		protected global::System.Web.UI.WebControls.TextBox txtJinRiAmount;
		protected global::System.Web.UI.WebControls.TextBox txtJinRiBerth;
		protected global::System.Web.UI.WebControls.TextBox txtJinRiRateWay;
		protected global::System.Web.UI.WebControls.TextBox txtJinRiUserType;
		protected global::System.Web.UI.WebControls.TextBox txtJinRiUserName;
		protected global::System.Web.UI.WebControls.TextBox txtJinRiVOYAGE;
		protected global::System.Web.UI.WebControls.TextBox txtServerAddress;
		protected global::System.Web.UI.WebControls.TextBox txtJinRiTiming;
		protected global::System.Web.UI.WebControls.TextBox txtC517natime;
		protected global::System.Web.UI.WebControls.TextBox txtC517name;
		protected global::System.Web.UI.WebControls.TextBox txtC517pid;
		protected global::System.Web.UI.WebControls.TextBox txtC517pidsafe;
		protected global::System.Web.UI.WebControls.TextBox txtYi8000name;
		protected global::System.Web.UI.WebControls.TextBox txtYi8000psword;
		protected global::System.Web.UI.WebControls.TextBox txtYi8000distime;
		protected global::System.Web.UI.WebControls.TextBox txtTicket380partner;
		protected global::System.Web.UI.WebControls.TextBox txtTicket380key;
		protected global::System.Web.UI.WebControls.TextBox txtTicket380time;
		protected global::System.Web.UI.WebControls.TextBox txtTicket380timeadd;
		protected global::System.Web.UI.WebControls.TextBox txtTicket380gettime;
		protected global::System.Web.UI.WebControls.TextBox txtC51bookname;
		protected global::System.Web.UI.WebControls.TextBox txtC51booktime;
		protected global::System.Web.UI.WebControls.TextBox txtC51bookyear;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
