//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.SystemConfig {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblAfterDays;
	protected global::System.Web.UI.WebControls.Label lblTimingDays;
	protected global::System.Web.UI.WebControls.Label lblAccount;
	protected global::System.Web.UI.WebControls.Label lblLogPath;
	protected global::System.Web.UI.WebControls.Label lblJinRiAmount;
	protected global::System.Web.UI.WebControls.Label lblJinRiBerth;
	protected global::System.Web.UI.WebControls.Label lblJinRiRateWay;
	protected global::System.Web.UI.WebControls.Label lblJinRiUserType;
	protected global::System.Web.UI.WebControls.Label lblJinRiUserName;
	protected global::System.Web.UI.WebControls.Label lblJinRiVOYAGE;
	protected global::System.Web.UI.WebControls.Label lblServerAddress;
	protected global::System.Web.UI.WebControls.Label lblJinRiTiming;
	protected global::System.Web.UI.WebControls.Label lblC517natime;
	protected global::System.Web.UI.WebControls.Label lblC517name;
	protected global::System.Web.UI.WebControls.Label lblC517pid;
	protected global::System.Web.UI.WebControls.Label lblC517pidsafe;
	protected global::System.Web.UI.WebControls.Label lblYi8000name;
	protected global::System.Web.UI.WebControls.Label lblYi8000psword;
	protected global::System.Web.UI.WebControls.Label lblYi8000distime;
	protected global::System.Web.UI.WebControls.Label lblTicket380partner;
	protected global::System.Web.UI.WebControls.Label lblTicket380key;
	protected global::System.Web.UI.WebControls.Label lblTicket380time;
	protected global::System.Web.UI.WebControls.Label lblTicket380timeadd;
	protected global::System.Web.UI.WebControls.Label lblTicket380gettime;
	protected global::System.Web.UI.WebControls.Label lblC51bookname;
	protected global::System.Web.UI.WebControls.Label lblC51booktime;
	protected global::System.Web.UI.WebControls.Label lblC51bookyear;


       
    }
}
