//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.GaiQianWangFanRetirement {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtnavigation_company;
		protected global::System.Web.UI.WebControls.TextBox txtair_line;
		protected global::System.Web.UI.WebControls.TextBox txtquchengSpace;
		protected global::System.Web.UI.WebControls.TextBox txthuichengSpace;
		protected global::System.Web.UI.WebControls.CheckBox chkinitiate_mode;
		protected global::System.Web.UI.WebControls.TextBox txtstartDate;
		protected global::System.Web.UI.WebControls.TextBox txtendDate;
		protected global::System.Web.UI.WebControls.TextBox txtrefund_rule;
		protected global::System.Web.UI.WebControls.TextBox txtchangedate_rule;
		protected global::System.Web.UI.WebControls.CheckBox chkis_allowed_sign;
		protected global::System.Web.UI.WebControls.TextBox txtsys_id;
		protected global::System.Web.UI.WebControls.TextBox txtplatform_type_id;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
