//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.Flight {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtcode;
		protected global::System.Web.UI.WebControls.TextBox txtcabin;
		protected global::System.Web.UI.WebControls.TextBox txtccabin;
		protected global::System.Web.UI.WebControls.TextBox txtdep;
		protected global::System.Web.UI.WebControls.TextBox txtarr;
		protected global::System.Web.UI.WebControls.TextBox txtdepDay;
		protected global::System.Web.UI.WebControls.TextBox txtdepTime;
		protected global::System.Web.UI.WebControls.TextBox txtarrTime;
		protected global::System.Web.UI.WebControls.TextBox txtrealCode;
		protected global::System.Web.UI.WebControls.TextBox txto_id;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
