//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.Flight {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblcode;
	protected global::System.Web.UI.WebControls.Label lblcabin;
	protected global::System.Web.UI.WebControls.Label lblccabin;
	protected global::System.Web.UI.WebControls.Label lbldep;
	protected global::System.Web.UI.WebControls.Label lblarr;
	protected global::System.Web.UI.WebControls.Label lbldepDay;
	protected global::System.Web.UI.WebControls.Label lbldepTime;
	protected global::System.Web.UI.WebControls.Label lblarrTime;
	protected global::System.Web.UI.WebControls.Label lblrealCode;
	protected global::System.Web.UI.WebControls.Label lblo_id;


       
    }
}
