//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.excGetRateList {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtPolicyId;
		protected global::System.Web.UI.WebControls.TextBox txtRateId;
		protected global::System.Web.UI.WebControls.TextBox txtScityE;
		protected global::System.Web.UI.WebControls.TextBox txtEcityE;
		protected global::System.Web.UI.WebControls.TextBox txtAirComE;
		protected global::System.Web.UI.WebControls.TextBox txtNoAirComE;
		protected global::System.Web.UI.WebControls.TextBox txtPolicyType;
		protected global::System.Web.UI.WebControls.TextBox txtCabin;
		protected global::System.Web.UI.WebControls.TextBox txtVoyageType;
		protected global::System.Web.UI.WebControls.TextBox txtUserType;
		protected global::System.Web.UI.WebControls.TextBox txtRateType;
		protected global::System.Web.UI.WebControls.TextBox txtDiscounts;
		protected global::System.Web.UI.WebControls.TextBox txtSdate;
		protected global::System.Web.UI.WebControls.TextBox txtEdate;
		protected global::System.Web.UI.WebControls.TextBox txtWorkTimBegin;
		protected global::System.Web.UI.WebControls.TextBox txtWorkTImeEnd;
		protected global::System.Web.UI.WebControls.TextBox txtRewards;
		protected global::System.Web.UI.WebControls.TextBox txtRemark;
		protected global::System.Web.UI.WebControls.TextBox txtET;
		protected global::System.Web.UI.WebControls.TextBox txtWP;
		protected global::System.Web.UI.WebControls.TextBox txtSP;
		protected global::System.Web.UI.WebControls.TextBox txtXF;
		protected global::System.Web.UI.WebControls.TextBox txtPromotionDiscount;
		protected global::System.Web.UI.WebControls.TextBox txtNewRateNo;
		protected global::System.Web.UI.WebControls.TextBox txtOfficeNum;
		protected global::System.Web.UI.WebControls.TextBox txtRefundTimeBegin;
		protected global::System.Web.UI.WebControls.TextBox txtRefundTimeEnd;
		protected global::System.Web.UI.WebControls.TextBox txtLastModifyTime;
		protected global::System.Web.UI.WebControls.TextBox txtLimitModels;
		protected global::System.Web.UI.WebControls.TextBox txtRefundRulesWay;
		protected global::System.Web.UI.WebControls.TextBox txtTPRemark;
		protected global::System.Web.UI.WebControls.TextBox txtChangeMsg;
		protected global::System.Web.UI.WebControls.TextBox txtInvalidMsg;
		protected global::System.Web.UI.WebControls.TextBox txtRiseCabin;
		protected global::System.Web.UI.WebControls.TextBox txtForeignMsg;
		protected global::System.Web.UI.WebControls.TextBox txtOutTicketPercent;
		protected global::System.Web.UI.WebControls.TextBox txtInvoiceMsg;
		protected global::System.Web.UI.WebControls.TextBox txtPrintInvoice;
		protected global::System.Web.UI.WebControls.TextBox txtSwitchPNR;
		protected global::System.Web.UI.WebControls.TextBox txtChange;
		protected global::System.Web.UI.WebControls.TextBox txtsed;
		protected global::System.Web.UI.WebControls.TextBox txtPlatForm;
		protected global::System.Web.UI.WebControls.TextBox txtAddTime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
