//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.excGetRateList {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblPolicyId;
	protected global::System.Web.UI.WebControls.Label lblRateId;
	protected global::System.Web.UI.WebControls.Label lblScityE;
	protected global::System.Web.UI.WebControls.Label lblEcityE;
	protected global::System.Web.UI.WebControls.Label lblAirComE;
	protected global::System.Web.UI.WebControls.Label lblNoAirComE;
	protected global::System.Web.UI.WebControls.Label lblPolicyType;
	protected global::System.Web.UI.WebControls.Label lblCabin;
	protected global::System.Web.UI.WebControls.Label lblVoyageType;
	protected global::System.Web.UI.WebControls.Label lblUserType;
	protected global::System.Web.UI.WebControls.Label lblRateType;
	protected global::System.Web.UI.WebControls.Label lblDiscounts;
	protected global::System.Web.UI.WebControls.Label lblSdate;
	protected global::System.Web.UI.WebControls.Label lblEdate;
	protected global::System.Web.UI.WebControls.Label lblWorkTimBegin;
	protected global::System.Web.UI.WebControls.Label lblWorkTImeEnd;
	protected global::System.Web.UI.WebControls.Label lblRewards;
	protected global::System.Web.UI.WebControls.Label lblRemark;
	protected global::System.Web.UI.WebControls.Label lblET;
	protected global::System.Web.UI.WebControls.Label lblWP;
	protected global::System.Web.UI.WebControls.Label lblSP;
	protected global::System.Web.UI.WebControls.Label lblXF;
	protected global::System.Web.UI.WebControls.Label lblPromotionDiscount;
	protected global::System.Web.UI.WebControls.Label lblNewRateNo;
	protected global::System.Web.UI.WebControls.Label lblOfficeNum;
	protected global::System.Web.UI.WebControls.Label lblRefundTimeBegin;
	protected global::System.Web.UI.WebControls.Label lblRefundTimeEnd;
	protected global::System.Web.UI.WebControls.Label lblLastModifyTime;
	protected global::System.Web.UI.WebControls.Label lblLimitModels;
	protected global::System.Web.UI.WebControls.Label lblRefundRulesWay;
	protected global::System.Web.UI.WebControls.Label lblTPRemark;
	protected global::System.Web.UI.WebControls.Label lblChangeMsg;
	protected global::System.Web.UI.WebControls.Label lblInvalidMsg;
	protected global::System.Web.UI.WebControls.Label lblRiseCabin;
	protected global::System.Web.UI.WebControls.Label lblForeignMsg;
	protected global::System.Web.UI.WebControls.Label lblOutTicketPercent;
	protected global::System.Web.UI.WebControls.Label lblInvoiceMsg;
	protected global::System.Web.UI.WebControls.Label lblPrintInvoice;
	protected global::System.Web.UI.WebControls.Label lblSwitchPNR;
	protected global::System.Web.UI.WebControls.Label lblChange;
	protected global::System.Web.UI.WebControls.Label lblsed;
	protected global::System.Web.UI.WebControls.Label lblPlatForm;
	protected global::System.Web.UI.WebControls.Label lblAddTime;


       
    }
}
