//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.policy_zy_Base {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtleavepoint;
		protected global::System.Web.UI.WebControls.TextBox txtleavemoney;
		protected global::System.Web.UI.WebControls.CheckBox chkis_filter;
		protected global::System.Web.UI.WebControls.TextBox txtstarttime;
		protected global::System.Web.UI.WebControls.TextBox txtendtime;
		protected global::System.Web.UI.WebControls.TextBox txtlowest_rebate;
		protected global::System.Web.UI.WebControls.TextBox txthighest_rebate;
		protected global::System.Web.UI.WebControls.TextBox txtearliest_advance_days;
		protected global::System.Web.UI.WebControls.TextBox txtnight_before_days;
		protected global::System.Web.UI.WebControls.TextBox txtpointSetType;
		protected global::System.Web.UI.WebControls.CheckBox chkisuploadfirstclass;
		protected global::System.Web.UI.WebControls.CheckBox chkisuploadchildclass;
		protected global::System.Web.UI.WebControls.CheckBox chkNFDpolicy;
		protected global::System.Web.UI.WebControls.TextBox txtflylimittime;
		protected global::System.Web.UI.WebControls.TextBox txtplatfromPolicy;
		protected global::System.Web.UI.WebControls.TextBox txtGWpolicy;
		protected global::System.Web.UI.WebControls.CheckBox chkuploadway;
		protected global::System.Web.UI.WebControls.CheckBox chkisuploadsharefight;
		protected global::System.Web.UI.WebControls.CheckBox chkaddpricejisuan;
		protected global::System.Web.UI.WebControls.TextBox txtaddpriceCovertType;
		protected global::System.Web.UI.WebControls.TextBox txtaddPriceSet;
		protected global::System.Web.UI.WebControls.TextBox txtlimitSit;
		protected global::System.Web.UI.WebControls.TextBox txtsaleSit;
		protected global::System.Web.UI.WebControls.CheckBox chkis_autoticket;
		protected global::System.Web.UI.WebControls.CheckBox chkis_Need;
		protected global::System.Web.UI.WebControls.TextBox txtisMail;
		protected global::System.Web.UI.WebControls.CheckBox chkisPay;
		protected global::System.Web.UI.WebControls.TextBox txtAuthorizeOffice;
		protected global::System.Web.UI.WebControls.TextBox txtrefund_rule;
		protected global::System.Web.UI.WebControls.TextBox txtchangedate_rule;
		protected global::System.Web.UI.WebControls.CheckBox chkis_allowed_sign;
		protected global::System.Web.UI.WebControls.CheckBox chkis_provide_regular_passenger_integral;
		protected global::System.Web.UI.WebControls.TextBox txtdocument_type;
		protected global::System.Web.UI.WebControls.TextBox txtmaxage;
		protected global::System.Web.UI.WebControls.TextBox txtminage;
		protected global::System.Web.UI.WebControls.TextBox txtclass_description;
		protected global::System.Web.UI.WebControls.TextBox txtspecial_ticketing_instructions;
		protected global::System.Web.UI.WebControls.TextBox txtlowest_price;
		protected global::System.Web.UI.WebControls.TextBox txthighest_price;
		protected global::System.Web.UI.WebControls.TextBox txtlastupdatetime;
		protected global::System.Web.UI.WebControls.TextBox txtsysuser_id;
		protected global::System.Web.UI.WebControls.TextBox txtplatform_id;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
