//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.policy_zy_Base {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblleavepoint;
	protected global::System.Web.UI.WebControls.Label lblleavemoney;
	protected global::System.Web.UI.WebControls.Label lblis_filter;
	protected global::System.Web.UI.WebControls.Label lblstarttime;
	protected global::System.Web.UI.WebControls.Label lblendtime;
	protected global::System.Web.UI.WebControls.Label lbllowest_rebate;
	protected global::System.Web.UI.WebControls.Label lblhighest_rebate;
	protected global::System.Web.UI.WebControls.Label lblearliest_advance_days;
	protected global::System.Web.UI.WebControls.Label lblnight_before_days;
	protected global::System.Web.UI.WebControls.Label lblpointSetType;
	protected global::System.Web.UI.WebControls.Label lblisuploadfirstclass;
	protected global::System.Web.UI.WebControls.Label lblisuploadchildclass;
	protected global::System.Web.UI.WebControls.Label lblNFDpolicy;
	protected global::System.Web.UI.WebControls.Label lblflylimittime;
	protected global::System.Web.UI.WebControls.Label lblplatfromPolicy;
	protected global::System.Web.UI.WebControls.Label lblGWpolicy;
	protected global::System.Web.UI.WebControls.Label lbluploadway;
	protected global::System.Web.UI.WebControls.Label lblisuploadsharefight;
	protected global::System.Web.UI.WebControls.Label lbladdpricejisuan;
	protected global::System.Web.UI.WebControls.Label lbladdpriceCovertType;
	protected global::System.Web.UI.WebControls.Label lbladdPriceSet;
	protected global::System.Web.UI.WebControls.Label lbllimitSit;
	protected global::System.Web.UI.WebControls.Label lblsaleSit;
	protected global::System.Web.UI.WebControls.Label lblis_autoticket;
	protected global::System.Web.UI.WebControls.Label lblis_Need;
	protected global::System.Web.UI.WebControls.Label lblisMail;
	protected global::System.Web.UI.WebControls.Label lblisPay;
	protected global::System.Web.UI.WebControls.Label lblAuthorizeOffice;
	protected global::System.Web.UI.WebControls.Label lblrefund_rule;
	protected global::System.Web.UI.WebControls.Label lblchangedate_rule;
	protected global::System.Web.UI.WebControls.Label lblis_allowed_sign;
	protected global::System.Web.UI.WebControls.Label lblis_provide_regular_passenger_integral;
	protected global::System.Web.UI.WebControls.Label lbldocument_type;
	protected global::System.Web.UI.WebControls.Label lblmaxage;
	protected global::System.Web.UI.WebControls.Label lblminage;
	protected global::System.Web.UI.WebControls.Label lblclass_description;
	protected global::System.Web.UI.WebControls.Label lblspecial_ticketing_instructions;
	protected global::System.Web.UI.WebControls.Label lbllowest_price;
	protected global::System.Web.UI.WebControls.Label lblhighest_price;
	protected global::System.Web.UI.WebControls.Label lbllastupdatetime;
	protected global::System.Web.UI.WebControls.Label lblsysuser_id;
	protected global::System.Web.UI.WebControls.Label lblplatform_id;


       
    }
}
