//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.platform_config {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblplatform_type_id;
	protected global::System.Web.UI.WebControls.Label lblusername;
	protected global::System.Web.UI.WebControls.Label lblpassword;
	protected global::System.Web.UI.WebControls.Label lblrealm_name;
	protected global::System.Web.UI.WebControls.Label lblbind_ip_address;
	protected global::System.Web.UI.WebControls.Label lblsys_user_id;


       
    }
}
