//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.sys_user {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtusername;
		protected global::System.Web.UI.WebControls.TextBox txtpassword;
		protected global::System.Web.UI.WebControls.TextBox txtCreateDate;
		protected global::System.Web.UI.WebControls.TextBox txtRoleList;
		protected global::System.Web.UI.WebControls.TextBox txtCheckAuthority;
		protected global::System.Web.UI.WebControls.CheckBox chkStop;
		protected global::System.Web.UI.WebControls.CheckBox chkIsModify;
		protected global::System.Web.UI.WebControls.TextBox txtRemark;
		protected global::System.Web.UI.WebControls.TextBox txtRealName;
		protected global::System.Web.UI.WebControls.TextBox txtCode;
		protected global::System.Web.UI.WebControls.TextBox txtGender;
		protected global::System.Web.UI.WebControls.TextBox txtMobile;
		protected global::System.Web.UI.WebControls.TextBox txtTelephone;
		protected global::System.Web.UI.WebControls.TextBox txtQQ;
		protected global::System.Web.UI.WebControls.TextBox txtEmaile;
		protected global::System.Web.UI.WebControls.TextBox txtCompany;
		protected global::System.Web.UI.WebControls.TextBox txtCompanyAddress;
		protected global::System.Web.UI.WebControls.TextBox txtParentID;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
