//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.policy_zy_leavepoint {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtnavigation_company;
		protected global::System.Web.UI.WebControls.TextBox txtair_line;
		protected global::System.Web.UI.WebControls.TextBox txtapplication_space;
		protected global::System.Web.UI.WebControls.TextBox txtrabate_number;
		protected global::System.Web.UI.WebControls.TextBox txtleave_point;
		protected global::System.Web.UI.WebControls.TextBox txtleave_money;
		protected global::System.Web.UI.WebControls.TextBox txtstartdate_ticket;
		protected global::System.Web.UI.WebControls.TextBox txtenddate_ticket;
		protected global::System.Web.UI.WebControls.TextBox txttraveldate;
		protected global::System.Web.UI.WebControls.CheckBox chkisleavepointandmoney;
		protected global::System.Web.UI.WebControls.CheckBox chkisSet;
		protected global::System.Web.UI.WebControls.TextBox txtremark;
		protected global::System.Web.UI.WebControls.TextBox txtchangedate;
		protected global::System.Web.UI.WebControls.TextBox txtplatform_id;
		protected global::System.Web.UI.WebControls.TextBox txtsys_id;
		protected global::System.Web.UI.WebControls.TextBox txtrabate_class;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
