//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.kuXunPolicyOptions {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txttolerate_stationary_point;
		protected global::System.Web.UI.WebControls.TextBox txttolerate_leave_money;
		protected global::System.Web.UI.WebControls.TextBox txtlowest_rebate;
		protected global::System.Web.UI.WebControls.TextBox txthighest_rebate;
		protected global::System.Web.UI.WebControls.TextBox txtearliest_advance_days;
		protected global::System.Web.UI.WebControls.TextBox txtnight_before_days;
		protected global::System.Web.UI.WebControls.TextBox txtrebate_class_set;
		protected global::System.Web.UI.WebControls.TextBox txtdiscount;
		protected global::System.Web.UI.WebControls.TextBox txtagent_rate;
		protected global::System.Web.UI.WebControls.TextBox txtinsurance_number;
		protected global::System.Web.UI.WebControls.CheckBox chkfoundPnr;
		protected global::System.Web.UI.WebControls.CheckBox chkis_mail_itinerary;
		protected global::System.Web.UI.WebControls.TextBox txtvalidatePatA;
		protected global::System.Web.UI.WebControls.TextBox txtvalidateClass;
		protected global::System.Web.UI.WebControls.TextBox txtrefund_change_rule;
		protected global::System.Web.UI.WebControls.TextBox txtsys_id;
		protected global::System.Web.UI.WebControls.TextBox txtplatform_type_id;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
