//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.orderInterfaceConfig {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtusername;
		protected global::System.Web.UI.WebControls.TextBox txtpassword;
		protected global::System.Web.UI.WebControls.TextBox txtorderAddress;
		protected global::System.Web.UI.WebControls.TextBox txtinterfaceAddress;
		protected global::System.Web.UI.WebControls.TextBox txtstartDate;
		protected global::System.Web.UI.WebControls.TextBox txtorderStatus;
		protected global::System.Web.UI.WebControls.CheckBox chkisAutomaticGainOrder;
		protected global::System.Web.UI.WebControls.CheckBox chkisAutomaticTicket;
		protected global::System.Web.UI.WebControls.TextBox txtflightCompany;
		protected global::System.Web.UI.WebControls.TextBox txtstartAirport;
		protected global::System.Web.UI.WebControls.TextBox txtendAirport;
		protected global::System.Web.UI.WebControls.TextBox txtmaxDeficit;
		protected global::System.Web.UI.WebControls.TextBox txtlinkPhone;
		protected global::System.Web.UI.WebControls.TextBox txtautomaticTicketPlat;
		protected global::System.Web.UI.WebControls.TextBox txtsys_id;
		protected global::System.Web.UI.WebControls.TextBox txtplatform_type_id;
		protected global::System.Web.UI.WebControls.TextBox txtrt_user;
		protected global::System.Web.UI.WebControls.TextBox txtrt_pwd;
		protected global::System.Web.UI.WebControls.TextBox txtEtermRT;
		protected global::System.Web.UI.WebControls.TextBox txtEtermRTuser;
		protected global::System.Web.UI.WebControls.TextBox txtEtermRTpwd;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
