//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.orderInterfaceConfig {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblusername;
	protected global::System.Web.UI.WebControls.Label lblpassword;
	protected global::System.Web.UI.WebControls.Label lblorderAddress;
	protected global::System.Web.UI.WebControls.Label lblinterfaceAddress;
	protected global::System.Web.UI.WebControls.Label lblstartDate;
	protected global::System.Web.UI.WebControls.Label lblorderStatus;
	protected global::System.Web.UI.WebControls.Label lblisAutomaticGainOrder;
	protected global::System.Web.UI.WebControls.Label lblisAutomaticTicket;
	protected global::System.Web.UI.WebControls.Label lblflightCompany;
	protected global::System.Web.UI.WebControls.Label lblstartAirport;
	protected global::System.Web.UI.WebControls.Label lblendAirport;
	protected global::System.Web.UI.WebControls.Label lblmaxDeficit;
	protected global::System.Web.UI.WebControls.Label lbllinkPhone;
	protected global::System.Web.UI.WebControls.Label lblautomaticTicketPlat;
	protected global::System.Web.UI.WebControls.Label lblsys_id;
	protected global::System.Web.UI.WebControls.Label lblplatform_type_id;
	protected global::System.Web.UI.WebControls.Label lblrt_user;
	protected global::System.Web.UI.WebControls.Label lblrt_pwd;
	protected global::System.Web.UI.WebControls.Label lblEtermRT;
	protected global::System.Web.UI.WebControls.Label lblEtermRTuser;
	protected global::System.Web.UI.WebControls.Label lblEtermRTpwd;


       
    }
}
