//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.API380Ticket {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblcode;
	protected global::System.Web.UI.WebControls.Label lblmessage;
	protected global::System.Web.UI.WebControls.Label lblbigpnr;
	protected global::System.Web.UI.WebControls.Label lblair;
	protected global::System.Web.UI.WebControls.Label lblpnr;
	protected global::System.Web.UI.WebControls.Label lblpaystatus;
	protected global::System.Web.UI.WebControls.Label lbltotaltax;
	protected global::System.Web.UI.WebControls.Label lblticketprice;
	protected global::System.Web.UI.WebControls.Label lblorderno;
	protected global::System.Web.UI.WebControls.Label lblplatformB2B_name_id;


       
    }
}
