//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policy.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://policy.jinri.cn/", ConfigurationName="ServiceReference3.JinRiRateServerSoap")]
    public interface JinRiRateServerSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/GetRateList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetRateList(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/GetRateList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetRateListAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/GetRateListByPNR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetRateListByPNR(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/GetRateListByPNR", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetRateListByPNRAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/GetRateByPolicyID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetRateByPolicyID(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/GetRateByPolicyID", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetRateByPolicyIDAsync(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JinRiRateServerSoapChannel : Policy.ServiceReference3.JinRiRateServerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JinRiRateServerSoapClient : System.ServiceModel.ClientBase<Policy.ServiceReference3.JinRiRateServerSoap>, Policy.ServiceReference3.JinRiRateServerSoap {
        
        public JinRiRateServerSoapClient() {
        }
        
        public JinRiRateServerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JinRiRateServerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JinRiRateServerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JinRiRateServerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetRateList(string data) {
            return base.Channel.GetRateList(data);
        }
        
        public System.Threading.Tasks.Task<string> GetRateListAsync(string data) {
            return base.Channel.GetRateListAsync(data);
        }
        
        public string GetRateListByPNR(string data) {
            return base.Channel.GetRateListByPNR(data);
        }
        
        public System.Threading.Tasks.Task<string> GetRateListByPNRAsync(string data) {
            return base.Channel.GetRateListByPNRAsync(data);
        }
        
        public string GetRateByPolicyID(string data) {
            return base.Channel.GetRateByPolicyID(data);
        }
        
        public System.Threading.Tasks.Task<string> GetRateByPolicyIDAsync(string data) {
            return base.Channel.GetRateByPolicyIDAsync(data);
        }
    }
}
