//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.Airport_Detail {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txtDate;
		protected global::System.Web.UI.WebControls.TextBox txtFrom_Code;
		protected global::System.Web.UI.WebControls.TextBox txtTo_Code;
		protected global::System.Web.UI.WebControls.TextBox txtStartCity;
		protected global::System.Web.UI.WebControls.TextBox txtArriveCity;
		protected global::System.Web.UI.WebControls.TextBox txtMileage;
		protected global::System.Web.UI.WebControls.TextBox txtFule_Adult;
		protected global::System.Web.UI.WebControls.TextBox txtFule_Child;
		protected global::System.Web.UI.WebControls.TextBox txtLine_Number;
		protected global::System.Web.UI.WebControls.TextBox txtShare_Line;
		protected global::System.Web.UI.WebControls.TextBox txtCompany;
		protected global::System.Web.UI.WebControls.TextBox txtStartCode;
		protected global::System.Web.UI.WebControls.TextBox txtStartAirport;
		protected global::System.Web.UI.WebControls.TextBox txtArriveCode;
		protected global::System.Web.UI.WebControls.TextBox txtArriveAirport;
		protected global::System.Web.UI.WebControls.TextBox txtStartTime;
		protected global::System.Web.UI.WebControls.TextBox txtArriveTime;
		protected global::System.Web.UI.WebControls.TextBox txtAirRax;
		protected global::System.Web.UI.WebControls.TextBox txtFuleRax;
		protected global::System.Web.UI.WebControls.TextBox txtFuelAdu;
		protected global::System.Web.UI.WebControls.TextBox txtFuelChd;
		protected global::System.Web.UI.WebControls.TextBox txtFood;
		protected global::System.Web.UI.WebControls.TextBox txtFood_Detail;
		protected global::System.Web.UI.WebControls.TextBox txtDirect_Flight;
		protected global::System.Web.UI.WebControls.TextBox txtType;
		protected global::System.Web.UI.WebControls.TextBox txtElectronic_Ticket;
		protected global::System.Web.UI.WebControls.TextBox txtStart_Terminal;
		protected global::System.Web.UI.WebControls.TextBox txtArrive_Terminal;
		protected global::System.Web.UI.WebControls.TextBox txtCabin;
		protected global::System.Web.UI.WebControls.TextBox txtChildCabin;
		protected global::System.Web.UI.WebControls.TextBox txtDiscount;
		protected global::System.Web.UI.WebControls.TextBox txtPrice;
		protected global::System.Web.UI.WebControls.TextBox txtSurplus_Seat_Qty;
		protected global::System.Web.UI.WebControls.TextBox txtCabin_Status;
		protected global::System.Web.UI.WebControls.TextBox txtCabin_Point;
		protected global::System.Web.UI.WebControls.TextBox txtValidity_Period;
		protected global::System.Web.UI.WebControls.TextBox txtReturn_Date;
		protected global::System.Web.UI.WebControls.TextBox txtValid_Date;
		protected global::System.Web.UI.WebControls.TextBox txtAddTime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
