//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.BaQianYiPolicy {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txtpolicy_num;
		protected global::System.Web.UI.WebControls.TextBox txtstartcity;
		protected global::System.Web.UI.WebControls.TextBox txtarrivecity;
		protected global::System.Web.UI.WebControls.TextBox txtairline;
		protected global::System.Web.UI.WebControls.TextBox txtfor_flight_no;
		protected global::System.Web.UI.WebControls.TextBox txtex_flight_no;
		protected global::System.Web.UI.WebControls.TextBox txtpolicy_ratype;
		protected global::System.Web.UI.WebControls.TextBox txtpoint;
		protected global::System.Web.UI.WebControls.TextBox txtcabin_discount;
		protected global::System.Web.UI.WebControls.TextBox txtstartdate;
		protected global::System.Web.UI.WebControls.TextBox txtarrivedate;
		protected global::System.Web.UI.WebControls.TextBox txtnomal_workday;
		protected global::System.Web.UI.WebControls.TextBox txtweekday;
		protected global::System.Web.UI.WebControls.TextBox txtvip_policy;
		protected global::System.Web.UI.WebControls.TextBox txtreturn_policy;
		protected global::System.Web.UI.WebControls.TextBox txtpolicy_type;
		protected global::System.Web.UI.WebControls.TextBox txtpolicy_note;
		protected global::System.Web.UI.WebControls.TextBox txtsupplier_id;
		protected global::System.Web.UI.WebControls.TextBox txtor_ticket_t;
		protected global::System.Web.UI.WebControls.TextBox txtweek_ticket_t;
		protected global::System.Web.UI.WebControls.TextBox txtpolicy_flight;
		protected global::System.Web.UI.WebControls.TextBox txtend_state;
		protected global::System.Web.UI.WebControls.TextBox txtoffice_code;
		protected global::System.Web.UI.WebControls.TextBox txtsalestart_date;
		protected global::System.Web.UI.WebControls.TextBox txtsaleend_date;
		protected global::System.Web.UI.WebControls.TextBox txtsupport_pay;
		protected global::System.Web.UI.WebControls.TextBox txtticket_efficient;
		protected global::System.Web.UI.WebControls.TextBox txtis_cgnum_ticket;
		protected global::System.Web.UI.WebControls.TextBox txtis_open_low;
		protected global::System.Web.UI.WebControls.TextBox txtaddtime;
		protected global::System.Web.UI.WebControls.TextBox txtlast_modify_time;
		protected global::System.Web.UI.WebControls.CheckBox chkIsUpload;
		protected global::System.Web.UI.WebControls.CheckBox chkIsUpdate;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
