//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.BaQianYiPolicy {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblpolicy_num;
	protected global::System.Web.UI.WebControls.Label lblstartcity;
	protected global::System.Web.UI.WebControls.Label lblarrivecity;
	protected global::System.Web.UI.WebControls.Label lblairline;
	protected global::System.Web.UI.WebControls.Label lblfor_flight_no;
	protected global::System.Web.UI.WebControls.Label lblex_flight_no;
	protected global::System.Web.UI.WebControls.Label lblpolicy_ratype;
	protected global::System.Web.UI.WebControls.Label lblpoint;
	protected global::System.Web.UI.WebControls.Label lblcabin_discount;
	protected global::System.Web.UI.WebControls.Label lblstartdate;
	protected global::System.Web.UI.WebControls.Label lblarrivedate;
	protected global::System.Web.UI.WebControls.Label lblnomal_workday;
	protected global::System.Web.UI.WebControls.Label lblweekday;
	protected global::System.Web.UI.WebControls.Label lblvip_policy;
	protected global::System.Web.UI.WebControls.Label lblreturn_policy;
	protected global::System.Web.UI.WebControls.Label lblpolicy_type;
	protected global::System.Web.UI.WebControls.Label lblpolicy_note;
	protected global::System.Web.UI.WebControls.Label lblsupplier_id;
	protected global::System.Web.UI.WebControls.Label lblor_ticket_t;
	protected global::System.Web.UI.WebControls.Label lblweek_ticket_t;
	protected global::System.Web.UI.WebControls.Label lblpolicy_flight;
	protected global::System.Web.UI.WebControls.Label lblend_state;
	protected global::System.Web.UI.WebControls.Label lbloffice_code;
	protected global::System.Web.UI.WebControls.Label lblsalestart_date;
	protected global::System.Web.UI.WebControls.Label lblsaleend_date;
	protected global::System.Web.UI.WebControls.Label lblsupport_pay;
	protected global::System.Web.UI.WebControls.Label lblticket_efficient;
	protected global::System.Web.UI.WebControls.Label lblis_cgnum_ticket;
	protected global::System.Web.UI.WebControls.Label lblis_open_low;
	protected global::System.Web.UI.WebControls.Label lbladdtime;
	protected global::System.Web.UI.WebControls.Label lbllast_modify_time;
	protected global::System.Web.UI.WebControls.Label lblIsUpload;
	protected global::System.Web.UI.WebControls.Label lblIsUpdate;


       
    }
}
