//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.SYS_MenuList {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txtText;
		protected global::System.Web.UI.WebControls.TextBox txtTabID;
		protected global::System.Web.UI.WebControls.TextBox txtNavigateUrl;
		protected global::System.Web.UI.WebControls.TextBox txtParentID;
		protected global::System.Web.UI.WebControls.CheckBox chkSingleClickExpand;
		protected global::System.Web.UI.WebControls.TextBox txtIcon;
		protected global::System.Web.UI.WebControls.CheckBox chkIsModule;
		protected global::System.Web.UI.WebControls.CheckBox chkIsFuntion;
		protected global::System.Web.UI.WebControls.TextBox txtOrdering;
		protected global::System.Web.UI.WebControls.CheckBox chkStop;
		protected global::System.Web.UI.WebControls.TextBox txtRemark;
		protected global::System.Web.UI.WebControls.TextBox txtVersion;
		protected global::System.Web.UI.WebControls.TextBox txtsort;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
