//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.SYS_MenuList {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblText;
	protected global::System.Web.UI.WebControls.Label lblTabID;
	protected global::System.Web.UI.WebControls.Label lblNavigateUrl;
	protected global::System.Web.UI.WebControls.Label lblParentID;
	protected global::System.Web.UI.WebControls.Label lblSingleClickExpand;
	protected global::System.Web.UI.WebControls.Label lblIcon;
	protected global::System.Web.UI.WebControls.Label lblIsModule;
	protected global::System.Web.UI.WebControls.Label lblIsFuntion;
	protected global::System.Web.UI.WebControls.Label lblOrdering;
	protected global::System.Web.UI.WebControls.Label lblStop;
	protected global::System.Web.UI.WebControls.Label lblRemark;
	protected global::System.Web.UI.WebControls.Label lblVersion;
	protected global::System.Web.UI.WebControls.Label lblsort;


       
    }
}
