//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policy.ServiceReference4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://getpolicy.b2b.service.version1_0.webservice.model.ltips.com/", ConfigurationName="ServiceReference4.GetPolicyService_1_0")]
    public interface GetPolicyService_1_0 {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractLiantuoReply))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractLiantuoRequest))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Policy.ServiceReference4.getPolicyResponse getPolicy(Policy.ServiceReference4.getPolicy request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Policy.ServiceReference4.getPolicyResponse> getPolicyAsync(Policy.ServiceReference4.getPolicy request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getpolicy.b2b.service.version1_0.webservice.model.ltips.com/")]
    public partial class getPolicyRequest : abstractLiantuoRequest {
        
        private string airlineCodeField;
        
        private string arrAirportCodeField;
        
        private string depAirportCodeField;
        
        private int needSpePricePolicyField;
        
        private bool needSpePricePolicyFieldSpecified;
        
        private int needSpeRulePolicyField;
        
        private bool needSpeRulePolicyFieldSpecified;
        
        private int pageNoField;
        
        private bool pageNoFieldSpecified;
        
        private string param1Field;
        
        private string param2Field;
        
        private string param3Field;
        
        private string param4Field;
        
        private int rowPerPageField;
        
        private bool rowPerPageFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string airlineCode {
            get {
                return this.airlineCodeField;
            }
            set {
                this.airlineCodeField = value;
                this.RaisePropertyChanged("airlineCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string arrAirportCode {
            get {
                return this.arrAirportCodeField;
            }
            set {
                this.arrAirportCodeField = value;
                this.RaisePropertyChanged("arrAirportCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string depAirportCode {
            get {
                return this.depAirportCodeField;
            }
            set {
                this.depAirportCodeField = value;
                this.RaisePropertyChanged("depAirportCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int needSpePricePolicy {
            get {
                return this.needSpePricePolicyField;
            }
            set {
                this.needSpePricePolicyField = value;
                this.RaisePropertyChanged("needSpePricePolicy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool needSpePricePolicySpecified {
            get {
                return this.needSpePricePolicyFieldSpecified;
            }
            set {
                this.needSpePricePolicyFieldSpecified = value;
                this.RaisePropertyChanged("needSpePricePolicySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int needSpeRulePolicy {
            get {
                return this.needSpeRulePolicyField;
            }
            set {
                this.needSpeRulePolicyField = value;
                this.RaisePropertyChanged("needSpeRulePolicy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool needSpeRulePolicySpecified {
            get {
                return this.needSpeRulePolicyFieldSpecified;
            }
            set {
                this.needSpeRulePolicyFieldSpecified = value;
                this.RaisePropertyChanged("needSpeRulePolicySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int pageNo {
            get {
                return this.pageNoField;
            }
            set {
                this.pageNoField = value;
                this.RaisePropertyChanged("pageNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageNoSpecified {
            get {
                return this.pageNoFieldSpecified;
            }
            set {
                this.pageNoFieldSpecified = value;
                this.RaisePropertyChanged("pageNoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
                this.RaisePropertyChanged("param1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
                this.RaisePropertyChanged("param2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string param3 {
            get {
                return this.param3Field;
            }
            set {
                this.param3Field = value;
                this.RaisePropertyChanged("param3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string param4 {
            get {
                return this.param4Field;
            }
            set {
                this.param4Field = value;
                this.RaisePropertyChanged("param4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int rowPerPage {
            get {
                return this.rowPerPageField;
            }
            set {
                this.rowPerPageField = value;
                this.RaisePropertyChanged("rowPerPage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rowPerPageSpecified {
            get {
                return this.rowPerPageFieldSpecified;
            }
            set {
                this.rowPerPageFieldSpecified = value;
                this.RaisePropertyChanged("rowPerPageSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getPolicyRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getpolicy.b2b.service.version1_0.webservice.model.ltips.com/")]
    public abstract partial class abstractLiantuoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string agencyCodeField;
        
        private string signField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string agencyCode {
            get {
                return this.agencyCodeField;
            }
            set {
                this.agencyCodeField = value;
                this.RaisePropertyChanged("agencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string sign {
            get {
                return this.signField;
            }
            set {
                this.signField = value;
                this.RaisePropertyChanged("sign");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getpolicy.b2b.service.version1_0.webservice.model.ltips.com/")]
    public partial class specialRules : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool acceptLimitPriceSalesField;
        
        private bool acceptLimitPriceSalesFieldSpecified;
        
        private int basePriceField;
        
        private bool basePriceFieldSpecified;
        
        private string changeRuleField;
        
        private double discountField;
        
        private bool discountFieldSpecified;
        
        private bool endorsementRuleField;
        
        private bool endorsementRuleFieldSpecified;
        
        private bool invoiceEnableField;
        
        private bool invoiceEnableFieldSpecified;
        
        private string invoicePriceField;
        
        private string invoiceTypeField;
        
        private bool needCreatePNRField;
        
        private bool needCreatePNRFieldSpecified;
        
        private bool needSwitchPNRField;
        
        private bool needSwitchPNRFieldSpecified;
        
        private bool needSwitchSeatClassField;
        
        private bool needSwitchSeatClassFieldSpecified;
        
        private string param1Field;
        
        private string param2Field;
        
        private string param3Field;
        
        private string param4Field;
        
        private int preferentialTypeField;
        
        private bool preferentialTypeFieldSpecified;
        
        private string preferentialValueField;
        
        private string refundRuleField;
        
        private string salesLimitPriceField;
        
        private int specialProductTypeField;
        
        private bool specialProductTypeFieldSpecified;
        
        private string ticketTimeField;
        
        private string vaidSeatClassOpenField;
        
        private string vtExplainField;
        
        private string vtFeeField;
        
        private bool vtLimitField;
        
        private bool vtLimitFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool acceptLimitPriceSales {
            get {
                return this.acceptLimitPriceSalesField;
            }
            set {
                this.acceptLimitPriceSalesField = value;
                this.RaisePropertyChanged("acceptLimitPriceSales");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool acceptLimitPriceSalesSpecified {
            get {
                return this.acceptLimitPriceSalesFieldSpecified;
            }
            set {
                this.acceptLimitPriceSalesFieldSpecified = value;
                this.RaisePropertyChanged("acceptLimitPriceSalesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int basePrice {
            get {
                return this.basePriceField;
            }
            set {
                this.basePriceField = value;
                this.RaisePropertyChanged("basePrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool basePriceSpecified {
            get {
                return this.basePriceFieldSpecified;
            }
            set {
                this.basePriceFieldSpecified = value;
                this.RaisePropertyChanged("basePriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string changeRule {
            get {
                return this.changeRuleField;
            }
            set {
                this.changeRuleField = value;
                this.RaisePropertyChanged("changeRule");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double discount {
            get {
                return this.discountField;
            }
            set {
                this.discountField = value;
                this.RaisePropertyChanged("discount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool discountSpecified {
            get {
                return this.discountFieldSpecified;
            }
            set {
                this.discountFieldSpecified = value;
                this.RaisePropertyChanged("discountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool endorsementRule {
            get {
                return this.endorsementRuleField;
            }
            set {
                this.endorsementRuleField = value;
                this.RaisePropertyChanged("endorsementRule");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endorsementRuleSpecified {
            get {
                return this.endorsementRuleFieldSpecified;
            }
            set {
                this.endorsementRuleFieldSpecified = value;
                this.RaisePropertyChanged("endorsementRuleSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool invoiceEnable {
            get {
                return this.invoiceEnableField;
            }
            set {
                this.invoiceEnableField = value;
                this.RaisePropertyChanged("invoiceEnable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool invoiceEnableSpecified {
            get {
                return this.invoiceEnableFieldSpecified;
            }
            set {
                this.invoiceEnableFieldSpecified = value;
                this.RaisePropertyChanged("invoiceEnableSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string invoicePrice {
            get {
                return this.invoicePriceField;
            }
            set {
                this.invoicePriceField = value;
                this.RaisePropertyChanged("invoicePrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string invoiceType {
            get {
                return this.invoiceTypeField;
            }
            set {
                this.invoiceTypeField = value;
                this.RaisePropertyChanged("invoiceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool needCreatePNR {
            get {
                return this.needCreatePNRField;
            }
            set {
                this.needCreatePNRField = value;
                this.RaisePropertyChanged("needCreatePNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool needCreatePNRSpecified {
            get {
                return this.needCreatePNRFieldSpecified;
            }
            set {
                this.needCreatePNRFieldSpecified = value;
                this.RaisePropertyChanged("needCreatePNRSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public bool needSwitchPNR {
            get {
                return this.needSwitchPNRField;
            }
            set {
                this.needSwitchPNRField = value;
                this.RaisePropertyChanged("needSwitchPNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool needSwitchPNRSpecified {
            get {
                return this.needSwitchPNRFieldSpecified;
            }
            set {
                this.needSwitchPNRFieldSpecified = value;
                this.RaisePropertyChanged("needSwitchPNRSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public bool needSwitchSeatClass {
            get {
                return this.needSwitchSeatClassField;
            }
            set {
                this.needSwitchSeatClassField = value;
                this.RaisePropertyChanged("needSwitchSeatClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool needSwitchSeatClassSpecified {
            get {
                return this.needSwitchSeatClassFieldSpecified;
            }
            set {
                this.needSwitchSeatClassFieldSpecified = value;
                this.RaisePropertyChanged("needSwitchSeatClassSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
                this.RaisePropertyChanged("param1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
                this.RaisePropertyChanged("param2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string param3 {
            get {
                return this.param3Field;
            }
            set {
                this.param3Field = value;
                this.RaisePropertyChanged("param3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string param4 {
            get {
                return this.param4Field;
            }
            set {
                this.param4Field = value;
                this.RaisePropertyChanged("param4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public int preferentialType {
            get {
                return this.preferentialTypeField;
            }
            set {
                this.preferentialTypeField = value;
                this.RaisePropertyChanged("preferentialType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool preferentialTypeSpecified {
            get {
                return this.preferentialTypeFieldSpecified;
            }
            set {
                this.preferentialTypeFieldSpecified = value;
                this.RaisePropertyChanged("preferentialTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string preferentialValue {
            get {
                return this.preferentialValueField;
            }
            set {
                this.preferentialValueField = value;
                this.RaisePropertyChanged("preferentialValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string refundRule {
            get {
                return this.refundRuleField;
            }
            set {
                this.refundRuleField = value;
                this.RaisePropertyChanged("refundRule");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string salesLimitPrice {
            get {
                return this.salesLimitPriceField;
            }
            set {
                this.salesLimitPriceField = value;
                this.RaisePropertyChanged("salesLimitPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public int specialProductType {
            get {
                return this.specialProductTypeField;
            }
            set {
                this.specialProductTypeField = value;
                this.RaisePropertyChanged("specialProductType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool specialProductTypeSpecified {
            get {
                return this.specialProductTypeFieldSpecified;
            }
            set {
                this.specialProductTypeFieldSpecified = value;
                this.RaisePropertyChanged("specialProductTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string ticketTime {
            get {
                return this.ticketTimeField;
            }
            set {
                this.ticketTimeField = value;
                this.RaisePropertyChanged("ticketTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string vaidSeatClassOpen {
            get {
                return this.vaidSeatClassOpenField;
            }
            set {
                this.vaidSeatClassOpenField = value;
                this.RaisePropertyChanged("vaidSeatClassOpen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string vtExplain {
            get {
                return this.vtExplainField;
            }
            set {
                this.vtExplainField = value;
                this.RaisePropertyChanged("vtExplain");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string vtFee {
            get {
                return this.vtFeeField;
            }
            set {
                this.vtFeeField = value;
                this.RaisePropertyChanged("vtFee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public bool vtLimit {
            get {
                return this.vtLimitField;
            }
            set {
                this.vtLimitField = value;
                this.RaisePropertyChanged("vtLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vtLimitSpecified {
            get {
                return this.vtLimitFieldSpecified;
            }
            set {
                this.vtLimitFieldSpecified = value;
                this.RaisePropertyChanged("vtLimitSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getpolicy.b2b.service.version1_0.webservice.model.ltips.com/")]
    public partial class wsPolicyData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string airlineCodeField;
        
        private string arrAirportExcludeField;
        
        private string baseinventoryNumField;
        
        private string commentField;
        
        private double commisionMoneyField;
        
        private bool commisionMoneyFieldSpecified;
        
        private float commisionPointField;
        
        private bool commisionPointFieldSpecified;
        
        private string depAirportExcludeField;
        
        private string depdateAndFlightSeatsExcludeField;
        
        private int earliestTicketDaysField;
        
        private bool earliestTicketDaysFieldSpecified;
        
        private string expiredDateField;
        
        private string flightCourseField;
        
        private string flightCycleField;
        
        private string flightNoExcludeField;
        
        private string flightNoIncludingField;
        
        private string inventoryPreFlightNoNumField;
        
        private string inventorySourceField;
        
        private int inventoryTypeField;
        
        private bool inventoryTypeFieldSpecified;
        
        private int isSpecialRulePolicyField;
        
        private bool isSpecialRulePolicyFieldSpecified;
        
        private int latestTicketDaysField;
        
        private bool latestTicketDaysFieldSpecified;
        
        private int needSwitchPNRField;
        
        private bool needSwitchPNRFieldSpecified;
        
        private string param1Field;
        
        private string param2Field;
        
        private string param3Field;
        
        private string param4Field;
        
        private string param5Field;
        
        private string policyBelongToField;
        
        private int policyIdField;
        
        private bool policyIdFieldSpecified;
        
        private int policyStatusField;
        
        private bool policyStatusFieldSpecified;
        
        private string policyTypeField;
        
        private string printTicketExpiredDateField;
        
        private string printTicketStartDateField;
        
        private int productTypeField;
        
        private bool productTypeFieldSpecified;
        
        private string routeTypeField;
        
        private string seatClassField;
        
        private int seatTypeField;
        
        private bool seatTypeFieldSpecified;
        
        private double specialPriceField;
        
        private bool specialPriceFieldSpecified;
        
        private specialRules specialRulesField;
        
        private string startDateField;
        
        private string supplyOfficeNoField;
        
        private string ticketSpeedField;
        
        private string vtWorkTimeField;
        
        private string workTimeField;
        
        private string workWeekField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string airlineCode {
            get {
                return this.airlineCodeField;
            }
            set {
                this.airlineCodeField = value;
                this.RaisePropertyChanged("airlineCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string arrAirportExclude {
            get {
                return this.arrAirportExcludeField;
            }
            set {
                this.arrAirportExcludeField = value;
                this.RaisePropertyChanged("arrAirportExclude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string baseinventoryNum {
            get {
                return this.baseinventoryNumField;
            }
            set {
                this.baseinventoryNumField = value;
                this.RaisePropertyChanged("baseinventoryNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("comment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double commisionMoney {
            get {
                return this.commisionMoneyField;
            }
            set {
                this.commisionMoneyField = value;
                this.RaisePropertyChanged("commisionMoney");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool commisionMoneySpecified {
            get {
                return this.commisionMoneyFieldSpecified;
            }
            set {
                this.commisionMoneyFieldSpecified = value;
                this.RaisePropertyChanged("commisionMoneySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public float commisionPoint {
            get {
                return this.commisionPointField;
            }
            set {
                this.commisionPointField = value;
                this.RaisePropertyChanged("commisionPoint");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool commisionPointSpecified {
            get {
                return this.commisionPointFieldSpecified;
            }
            set {
                this.commisionPointFieldSpecified = value;
                this.RaisePropertyChanged("commisionPointSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string depAirportExclude {
            get {
                return this.depAirportExcludeField;
            }
            set {
                this.depAirportExcludeField = value;
                this.RaisePropertyChanged("depAirportExclude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string depdateAndFlightSeatsExclude {
            get {
                return this.depdateAndFlightSeatsExcludeField;
            }
            set {
                this.depdateAndFlightSeatsExcludeField = value;
                this.RaisePropertyChanged("depdateAndFlightSeatsExclude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int earliestTicketDays {
            get {
                return this.earliestTicketDaysField;
            }
            set {
                this.earliestTicketDaysField = value;
                this.RaisePropertyChanged("earliestTicketDays");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool earliestTicketDaysSpecified {
            get {
                return this.earliestTicketDaysFieldSpecified;
            }
            set {
                this.earliestTicketDaysFieldSpecified = value;
                this.RaisePropertyChanged("earliestTicketDaysSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string expiredDate {
            get {
                return this.expiredDateField;
            }
            set {
                this.expiredDateField = value;
                this.RaisePropertyChanged("expiredDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string flightCourse {
            get {
                return this.flightCourseField;
            }
            set {
                this.flightCourseField = value;
                this.RaisePropertyChanged("flightCourse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string flightCycle {
            get {
                return this.flightCycleField;
            }
            set {
                this.flightCycleField = value;
                this.RaisePropertyChanged("flightCycle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string flightNoExclude {
            get {
                return this.flightNoExcludeField;
            }
            set {
                this.flightNoExcludeField = value;
                this.RaisePropertyChanged("flightNoExclude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string flightNoIncluding {
            get {
                return this.flightNoIncludingField;
            }
            set {
                this.flightNoIncludingField = value;
                this.RaisePropertyChanged("flightNoIncluding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string inventoryPreFlightNoNum {
            get {
                return this.inventoryPreFlightNoNumField;
            }
            set {
                this.inventoryPreFlightNoNumField = value;
                this.RaisePropertyChanged("inventoryPreFlightNoNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string inventorySource {
            get {
                return this.inventorySourceField;
            }
            set {
                this.inventorySourceField = value;
                this.RaisePropertyChanged("inventorySource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public int inventoryType {
            get {
                return this.inventoryTypeField;
            }
            set {
                this.inventoryTypeField = value;
                this.RaisePropertyChanged("inventoryType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool inventoryTypeSpecified {
            get {
                return this.inventoryTypeFieldSpecified;
            }
            set {
                this.inventoryTypeFieldSpecified = value;
                this.RaisePropertyChanged("inventoryTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public int isSpecialRulePolicy {
            get {
                return this.isSpecialRulePolicyField;
            }
            set {
                this.isSpecialRulePolicyField = value;
                this.RaisePropertyChanged("isSpecialRulePolicy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isSpecialRulePolicySpecified {
            get {
                return this.isSpecialRulePolicyFieldSpecified;
            }
            set {
                this.isSpecialRulePolicyFieldSpecified = value;
                this.RaisePropertyChanged("isSpecialRulePolicySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public int latestTicketDays {
            get {
                return this.latestTicketDaysField;
            }
            set {
                this.latestTicketDaysField = value;
                this.RaisePropertyChanged("latestTicketDays");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool latestTicketDaysSpecified {
            get {
                return this.latestTicketDaysFieldSpecified;
            }
            set {
                this.latestTicketDaysFieldSpecified = value;
                this.RaisePropertyChanged("latestTicketDaysSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public int needSwitchPNR {
            get {
                return this.needSwitchPNRField;
            }
            set {
                this.needSwitchPNRField = value;
                this.RaisePropertyChanged("needSwitchPNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool needSwitchPNRSpecified {
            get {
                return this.needSwitchPNRFieldSpecified;
            }
            set {
                this.needSwitchPNRFieldSpecified = value;
                this.RaisePropertyChanged("needSwitchPNRSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
                this.RaisePropertyChanged("param1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
                this.RaisePropertyChanged("param2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string param3 {
            get {
                return this.param3Field;
            }
            set {
                this.param3Field = value;
                this.RaisePropertyChanged("param3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string param4 {
            get {
                return this.param4Field;
            }
            set {
                this.param4Field = value;
                this.RaisePropertyChanged("param4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string param5 {
            get {
                return this.param5Field;
            }
            set {
                this.param5Field = value;
                this.RaisePropertyChanged("param5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string policyBelongTo {
            get {
                return this.policyBelongToField;
            }
            set {
                this.policyBelongToField = value;
                this.RaisePropertyChanged("policyBelongTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public int policyId {
            get {
                return this.policyIdField;
            }
            set {
                this.policyIdField = value;
                this.RaisePropertyChanged("policyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool policyIdSpecified {
            get {
                return this.policyIdFieldSpecified;
            }
            set {
                this.policyIdFieldSpecified = value;
                this.RaisePropertyChanged("policyIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public int policyStatus {
            get {
                return this.policyStatusField;
            }
            set {
                this.policyStatusField = value;
                this.RaisePropertyChanged("policyStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool policyStatusSpecified {
            get {
                return this.policyStatusFieldSpecified;
            }
            set {
                this.policyStatusFieldSpecified = value;
                this.RaisePropertyChanged("policyStatusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string policyType {
            get {
                return this.policyTypeField;
            }
            set {
                this.policyTypeField = value;
                this.RaisePropertyChanged("policyType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string printTicketExpiredDate {
            get {
                return this.printTicketExpiredDateField;
            }
            set {
                this.printTicketExpiredDateField = value;
                this.RaisePropertyChanged("printTicketExpiredDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string printTicketStartDate {
            get {
                return this.printTicketStartDateField;
            }
            set {
                this.printTicketStartDateField = value;
                this.RaisePropertyChanged("printTicketStartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public int productType {
            get {
                return this.productTypeField;
            }
            set {
                this.productTypeField = value;
                this.RaisePropertyChanged("productType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool productTypeSpecified {
            get {
                return this.productTypeFieldSpecified;
            }
            set {
                this.productTypeFieldSpecified = value;
                this.RaisePropertyChanged("productTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string routeType {
            get {
                return this.routeTypeField;
            }
            set {
                this.routeTypeField = value;
                this.RaisePropertyChanged("routeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string seatClass {
            get {
                return this.seatClassField;
            }
            set {
                this.seatClassField = value;
                this.RaisePropertyChanged("seatClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public int seatType {
            get {
                return this.seatTypeField;
            }
            set {
                this.seatTypeField = value;
                this.RaisePropertyChanged("seatType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool seatTypeSpecified {
            get {
                return this.seatTypeFieldSpecified;
            }
            set {
                this.seatTypeFieldSpecified = value;
                this.RaisePropertyChanged("seatTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public double specialPrice {
            get {
                return this.specialPriceField;
            }
            set {
                this.specialPriceField = value;
                this.RaisePropertyChanged("specialPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool specialPriceSpecified {
            get {
                return this.specialPriceFieldSpecified;
            }
            set {
                this.specialPriceFieldSpecified = value;
                this.RaisePropertyChanged("specialPriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public specialRules specialRules {
            get {
                return this.specialRulesField;
            }
            set {
                this.specialRulesField = value;
                this.RaisePropertyChanged("specialRules");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("startDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string supplyOfficeNo {
            get {
                return this.supplyOfficeNoField;
            }
            set {
                this.supplyOfficeNoField = value;
                this.RaisePropertyChanged("supplyOfficeNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string ticketSpeed {
            get {
                return this.ticketSpeedField;
            }
            set {
                this.ticketSpeedField = value;
                this.RaisePropertyChanged("ticketSpeed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string vtWorkTime {
            get {
                return this.vtWorkTimeField;
            }
            set {
                this.vtWorkTimeField = value;
                this.RaisePropertyChanged("vtWorkTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string workTime {
            get {
                return this.workTimeField;
            }
            set {
                this.workTimeField = value;
                this.RaisePropertyChanged("workTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string workWeek {
            get {
                return this.workWeekField;
            }
            set {
                this.workWeekField = value;
                this.RaisePropertyChanged("workWeek");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getPolicyReply))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getpolicy.b2b.service.version1_0.webservice.model.ltips.com/")]
    public abstract partial class abstractLiantuoReply : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnCodeField;
        
        private string returnMessageField;
        
        private string returnStackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("returnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string returnMessage {
            get {
                return this.returnMessageField;
            }
            set {
                this.returnMessageField = value;
                this.RaisePropertyChanged("returnMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string returnStackTrace {
            get {
                return this.returnStackTraceField;
            }
            set {
                this.returnStackTraceField = value;
                this.RaisePropertyChanged("returnStackTrace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getpolicy.b2b.service.version1_0.webservice.model.ltips.com/")]
    public partial class getPolicyReply : abstractLiantuoReply {
        
        private string param1Field;
        
        private string param2Field;
        
        private string param3Field;
        
        private string param4Field;
        
        private wsPolicyData[] policyDatasField;
        
        private int totalPageCountField;
        
        private bool totalPageCountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string param1 {
            get {
                return this.param1Field;
            }
            set {
                this.param1Field = value;
                this.RaisePropertyChanged("param1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string param2 {
            get {
                return this.param2Field;
            }
            set {
                this.param2Field = value;
                this.RaisePropertyChanged("param2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string param3 {
            get {
                return this.param3Field;
            }
            set {
                this.param3Field = value;
                this.RaisePropertyChanged("param3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string param4 {
            get {
                return this.param4Field;
            }
            set {
                this.param4Field = value;
                this.RaisePropertyChanged("param4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("policyDatas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public wsPolicyData[] policyDatas {
            get {
                return this.policyDatasField;
            }
            set {
                this.policyDatasField = value;
                this.RaisePropertyChanged("policyDatas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int totalPageCount {
            get {
                return this.totalPageCountField;
            }
            set {
                this.totalPageCountField = value;
                this.RaisePropertyChanged("totalPageCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalPageCountSpecified {
            get {
                return this.totalPageCountFieldSpecified;
            }
            set {
                this.totalPageCountFieldSpecified = value;
                this.RaisePropertyChanged("totalPageCountSpecified");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPolicy", WrapperNamespace="http://getpolicy.b2b.service.version1_0.webservice.model.ltips.com/", IsWrapped=true)]
    public partial class getPolicy {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://getpolicy.b2b.service.version1_0.webservice.model.ltips.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Policy.ServiceReference4.getPolicyRequest request;
        
        public getPolicy() {
        }
        
        public getPolicy(Policy.ServiceReference4.getPolicyRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPolicyResponse", WrapperNamespace="http://getpolicy.b2b.service.version1_0.webservice.model.ltips.com/", IsWrapped=true)]
    public partial class getPolicyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://getpolicy.b2b.service.version1_0.webservice.model.ltips.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Policy.ServiceReference4.getPolicyReply @return;
        
        public getPolicyResponse() {
        }
        
        public getPolicyResponse(Policy.ServiceReference4.getPolicyReply @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetPolicyService_1_0Channel : Policy.ServiceReference4.GetPolicyService_1_0, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPolicyService_1_0Client : System.ServiceModel.ClientBase<Policy.ServiceReference4.GetPolicyService_1_0>, Policy.ServiceReference4.GetPolicyService_1_0 {
        
        public GetPolicyService_1_0Client() {
        }
        
        public GetPolicyService_1_0Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetPolicyService_1_0Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetPolicyService_1_0Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetPolicyService_1_0Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Policy.ServiceReference4.getPolicyResponse Policy.ServiceReference4.GetPolicyService_1_0.getPolicy(Policy.ServiceReference4.getPolicy request) {
            return base.Channel.getPolicy(request);
        }
        
        public Policy.ServiceReference4.getPolicyReply getPolicy(Policy.ServiceReference4.getPolicyRequest request) {
            Policy.ServiceReference4.getPolicy inValue = new Policy.ServiceReference4.getPolicy();
            inValue.request = request;
            Policy.ServiceReference4.getPolicyResponse retVal = ((Policy.ServiceReference4.GetPolicyService_1_0)(this)).getPolicy(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Policy.ServiceReference4.getPolicyResponse> Policy.ServiceReference4.GetPolicyService_1_0.getPolicyAsync(Policy.ServiceReference4.getPolicy request) {
            return base.Channel.getPolicyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Policy.ServiceReference4.getPolicyResponse> getPolicyAsync(Policy.ServiceReference4.getPolicyRequest request) {
            Policy.ServiceReference4.getPolicy inValue = new Policy.ServiceReference4.getPolicy();
            inValue.request = request;
            return ((Policy.ServiceReference4.GetPolicyService_1_0)(this)).getPolicyAsync(inValue);
        }
    }
}
