//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.Ticket380Policy {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txtpolicy_id;
		protected global::System.Web.UI.WebControls.TextBox txtair_comp;
		protected global::System.Web.UI.WebControls.TextBox txtstart_city;
		protected global::System.Web.UI.WebControls.TextBox txtarr_city;
		protected global::System.Web.UI.WebControls.TextBox txtflight;
		protected global::System.Web.UI.WebControls.TextBox txtcabin;
		protected global::System.Web.UI.WebControls.TextBox txtshare_line;
		protected global::System.Web.UI.WebControls.TextBox txtcabinprice;
		protected global::System.Web.UI.WebControls.TextBox txtpoint;
		protected global::System.Web.UI.WebControls.TextBox txtnakednum;
		protected global::System.Web.UI.WebControls.TextBox txtis_auto_tic;
		protected global::System.Web.UI.WebControls.TextBox txtlogtime;
		protected global::System.Web.UI.WebControls.TextBox txtdeptime;
		protected global::System.Web.UI.WebControls.TextBox txtprice;
		protected global::System.Web.UI.WebControls.TextBox txtremark;
		protected global::System.Web.UI.WebControls.TextBox txtfsdate;
		protected global::System.Web.UI.WebControls.TextBox txtfedate;
		protected global::System.Web.UI.WebControls.TextBox txtsale_sdate;
		protected global::System.Web.UI.WebControls.TextBox txtsale_edate;
		protected global::System.Web.UI.WebControls.TextBox txtAddTime;
		protected global::System.Web.UI.WebControls.CheckBox chkIsUpload;
		protected global::System.Web.UI.WebControls.CheckBox chkIsUpdate;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
