//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.Ticket380Policy {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblpolicy_id;
	protected global::System.Web.UI.WebControls.Label lblair_comp;
	protected global::System.Web.UI.WebControls.Label lblstart_city;
	protected global::System.Web.UI.WebControls.Label lblarr_city;
	protected global::System.Web.UI.WebControls.Label lblflight;
	protected global::System.Web.UI.WebControls.Label lblcabin;
	protected global::System.Web.UI.WebControls.Label lblshare_line;
	protected global::System.Web.UI.WebControls.Label lblcabinprice;
	protected global::System.Web.UI.WebControls.Label lblpoint;
	protected global::System.Web.UI.WebControls.Label lblnakednum;
	protected global::System.Web.UI.WebControls.Label lblis_auto_tic;
	protected global::System.Web.UI.WebControls.Label lbllogtime;
	protected global::System.Web.UI.WebControls.Label lbldeptime;
	protected global::System.Web.UI.WebControls.Label lblprice;
	protected global::System.Web.UI.WebControls.Label lblremark;
	protected global::System.Web.UI.WebControls.Label lblfsdate;
	protected global::System.Web.UI.WebControls.Label lblfedate;
	protected global::System.Web.UI.WebControls.Label lblsale_sdate;
	protected global::System.Web.UI.WebControls.Label lblsale_edate;
	protected global::System.Web.UI.WebControls.Label lblAddTime;
	protected global::System.Web.UI.WebControls.Label lblIsUpload;
	protected global::System.Web.UI.WebControls.Label lblIsUpdate;


       
    }
}
