//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.Policy {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtflightcode;
		protected global::System.Web.UI.WebControls.TextBox txtpolicyCode;
		protected global::System.Web.UI.WebControls.TextBox txtdpt;
		protected global::System.Web.UI.WebControls.TextBox txtarr;
		protected global::System.Web.UI.WebControls.TextBox txtflightNumLimit;
		protected global::System.Web.UI.WebControls.TextBox txtflightcondition;
		protected global::System.Web.UI.WebControls.TextBox txtdaycondition;
		protected global::System.Web.UI.WebControls.TextBox txtcabin;
		protected global::System.Web.UI.WebControls.TextBox txtdiscountType;
		protected global::System.Web.UI.WebControls.TextBox txtdiscountValue;
		protected global::System.Web.UI.WebControls.TextBox txtreturnpoint;
		protected global::System.Web.UI.WebControls.TextBox txtreturnprice;
		protected global::System.Web.UI.WebControls.TextBox txtstartdate_ticket;
		protected global::System.Web.UI.WebControls.TextBox txtenfdate_ticket;
		protected global::System.Web.UI.WebControls.TextBox txtstartdate;
		protected global::System.Web.UI.WebControls.TextBox txtenddate;
		protected global::System.Web.UI.WebControls.TextBox txtbeforeValidDay;
		protected global::System.Web.UI.WebControls.TextBox txtbacknote;
		protected global::System.Web.UI.WebControls.TextBox txtcabinnote;
		protected global::System.Web.UI.WebControls.CheckBox chkautoTicket;
		protected global::System.Web.UI.WebControls.CheckBox chkshared;
		protected global::System.Web.UI.WebControls.TextBox txtofficeno;
		protected global::System.Web.UI.WebControls.TextBox txtktype;
		protected global::System.Web.UI.WebControls.TextBox txtcheckCycleTime;
		protected global::System.Web.UI.WebControls.TextBox txtautoCheckOverTime;
		protected global::System.Web.UI.WebControls.TextBox txtmanualCheckOverTime;
		protected global::System.Web.UI.WebControls.TextBox txtpolicy;
		protected global::System.Web.UI.WebControls.TextBox txtdownDiscount;
		protected global::System.Web.UI.WebControls.CheckBox chkpata;
		protected global::System.Web.UI.WebControls.TextBox txtspecialRule;
		protected global::System.Web.UI.WebControls.TextBox txtallCabin;
		protected global::System.Web.UI.WebControls.CheckBox chkcanPay;
		protected global::System.Web.UI.WebControls.TextBox txtdeptTimeSlot;
		protected global::System.Web.UI.WebControls.CheckBox chkneedPnr;
		protected global::System.Web.UI.WebControls.TextBox txtone_flightlimit;
		protected global::System.Web.UI.WebControls.TextBox txtone_limitnum;
		protected global::System.Web.UI.WebControls.TextBox txttwo_flightlimit;
		protected global::System.Web.UI.WebControls.TextBox txttwo_limitnum;
		protected global::System.Web.UI.WebControls.TextBox txtone_daylimit;
		protected global::System.Web.UI.WebControls.TextBox txttwo_daylimit;
		protected global::System.Web.UI.WebControls.TextBox txtgocabin;
		protected global::System.Web.UI.WebControls.TextBox txtbackcabin;
		protected global::System.Web.UI.WebControls.TextBox txtone_startdate;
		protected global::System.Web.UI.WebControls.TextBox txtone_enddate;
		protected global::System.Web.UI.WebControls.TextBox txttwo_startdate;
		protected global::System.Web.UI.WebControls.TextBox txttwo_enddate;
		protected global::System.Web.UI.WebControls.TextBox txtshort_stoptime;
		protected global::System.Web.UI.WebControls.TextBox txtlong_stoptime;
		protected global::System.Web.UI.WebControls.TextBox txtcosttype;
		protected global::System.Web.UI.WebControls.TextBox txtcostPrice;
		protected global::System.Web.UI.WebControls.TextBox txtproxyPrice;
		protected global::System.Web.UI.WebControls.TextBox txtbackPrice;
		protected global::System.Web.UI.WebControls.TextBox txtpolicySource;
		protected global::System.Web.UI.WebControls.TextBox txtxcd;
		protected global::System.Web.UI.WebControls.TextBox txtreturnRule;
		protected global::System.Web.UI.WebControls.TextBox txtchangeRule;
		protected global::System.Web.UI.WebControls.CheckBox chkendorsement;
		protected global::System.Web.UI.WebControls.CheckBox chkflyerpoints;
		protected global::System.Web.UI.WebControls.TextBox txtcardType;
		protected global::System.Web.UI.WebControls.TextBox txtmaxAge;
		protected global::System.Web.UI.WebControls.TextBox txtminAge;
		protected global::System.Web.UI.WebControls.TextBox txtsys_id;
		protected global::System.Web.UI.WebControls.TextBox txtuploadPolicyType;
		protected global::System.Web.UI.WebControls.TextBox txtearliestBeforeValidDay;
		protected global::System.Web.UI.WebControls.TextBox txtisUpload;
		protected global::System.Web.UI.WebControls.TextBox txtimportTime;
		protected global::System.Web.UI.WebControls.TextBox txtuploadPlat;
		protected global::System.Web.UI.WebControls.TextBox txtuploadResult;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
