//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.Policy {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblflightcode;
	protected global::System.Web.UI.WebControls.Label lblpolicyCode;
	protected global::System.Web.UI.WebControls.Label lbldpt;
	protected global::System.Web.UI.WebControls.Label lblarr;
	protected global::System.Web.UI.WebControls.Label lblflightNumLimit;
	protected global::System.Web.UI.WebControls.Label lblflightcondition;
	protected global::System.Web.UI.WebControls.Label lbldaycondition;
	protected global::System.Web.UI.WebControls.Label lblcabin;
	protected global::System.Web.UI.WebControls.Label lbldiscountType;
	protected global::System.Web.UI.WebControls.Label lbldiscountValue;
	protected global::System.Web.UI.WebControls.Label lblreturnpoint;
	protected global::System.Web.UI.WebControls.Label lblreturnprice;
	protected global::System.Web.UI.WebControls.Label lblstartdate_ticket;
	protected global::System.Web.UI.WebControls.Label lblenfdate_ticket;
	protected global::System.Web.UI.WebControls.Label lblstartdate;
	protected global::System.Web.UI.WebControls.Label lblenddate;
	protected global::System.Web.UI.WebControls.Label lblbeforeValidDay;
	protected global::System.Web.UI.WebControls.Label lblbacknote;
	protected global::System.Web.UI.WebControls.Label lblcabinnote;
	protected global::System.Web.UI.WebControls.Label lblautoTicket;
	protected global::System.Web.UI.WebControls.Label lblshared;
	protected global::System.Web.UI.WebControls.Label lblofficeno;
	protected global::System.Web.UI.WebControls.Label lblktype;
	protected global::System.Web.UI.WebControls.Label lblcheckCycleTime;
	protected global::System.Web.UI.WebControls.Label lblautoCheckOverTime;
	protected global::System.Web.UI.WebControls.Label lblmanualCheckOverTime;
	protected global::System.Web.UI.WebControls.Label lblpolicy;
	protected global::System.Web.UI.WebControls.Label lbldownDiscount;
	protected global::System.Web.UI.WebControls.Label lblpata;
	protected global::System.Web.UI.WebControls.Label lblspecialRule;
	protected global::System.Web.UI.WebControls.Label lblallCabin;
	protected global::System.Web.UI.WebControls.Label lblcanPay;
	protected global::System.Web.UI.WebControls.Label lbldeptTimeSlot;
	protected global::System.Web.UI.WebControls.Label lblneedPnr;
	protected global::System.Web.UI.WebControls.Label lblone_flightlimit;
	protected global::System.Web.UI.WebControls.Label lblone_limitnum;
	protected global::System.Web.UI.WebControls.Label lbltwo_flightlimit;
	protected global::System.Web.UI.WebControls.Label lbltwo_limitnum;
	protected global::System.Web.UI.WebControls.Label lblone_daylimit;
	protected global::System.Web.UI.WebControls.Label lbltwo_daylimit;
	protected global::System.Web.UI.WebControls.Label lblgocabin;
	protected global::System.Web.UI.WebControls.Label lblbackcabin;
	protected global::System.Web.UI.WebControls.Label lblone_startdate;
	protected global::System.Web.UI.WebControls.Label lblone_enddate;
	protected global::System.Web.UI.WebControls.Label lbltwo_startdate;
	protected global::System.Web.UI.WebControls.Label lbltwo_enddate;
	protected global::System.Web.UI.WebControls.Label lblshort_stoptime;
	protected global::System.Web.UI.WebControls.Label lbllong_stoptime;
	protected global::System.Web.UI.WebControls.Label lblcosttype;
	protected global::System.Web.UI.WebControls.Label lblcostPrice;
	protected global::System.Web.UI.WebControls.Label lblproxyPrice;
	protected global::System.Web.UI.WebControls.Label lblbackPrice;
	protected global::System.Web.UI.WebControls.Label lblpolicySource;
	protected global::System.Web.UI.WebControls.Label lblxcd;
	protected global::System.Web.UI.WebControls.Label lblreturnRule;
	protected global::System.Web.UI.WebControls.Label lblchangeRule;
	protected global::System.Web.UI.WebControls.Label lblendorsement;
	protected global::System.Web.UI.WebControls.Label lblflyerpoints;
	protected global::System.Web.UI.WebControls.Label lblcardType;
	protected global::System.Web.UI.WebControls.Label lblmaxAge;
	protected global::System.Web.UI.WebControls.Label lblminAge;
	protected global::System.Web.UI.WebControls.Label lblsys_id;
	protected global::System.Web.UI.WebControls.Label lbluploadPolicyType;
	protected global::System.Web.UI.WebControls.Label lblearliestBeforeValidDay;
	protected global::System.Web.UI.WebControls.Label lblisUpload;
	protected global::System.Web.UI.WebControls.Label lblimportTime;
	protected global::System.Web.UI.WebControls.Label lbluploadPlat;
	protected global::System.Web.UI.WebControls.Label lbluploadResult;


       
    }
}
