//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.uploadTask {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtexecution_frequency;
		protected global::System.Web.UI.WebControls.TextBox txtexecution_time;
		protected global::System.Web.UI.WebControls.TextBox txtupload_platFrom;
		protected global::System.Web.UI.WebControls.TextBox txtpolicy_class;
		protected global::System.Web.UI.WebControls.TextBox txtupload_class;
		protected global::System.Web.UI.WebControls.CheckBox chkuploadPlatFrom_specialPolicies;
		protected global::System.Web.UI.WebControls.TextBox txtpolicySource;
		protected global::System.Web.UI.WebControls.TextBox txttripType;
		protected global::System.Web.UI.WebControls.TextBox txtexecute_number;
		protected global::System.Web.UI.WebControls.CheckBox chkcondition;
		protected global::System.Web.UI.WebControls.TextBox txtsys_id;
		protected global::System.Web.UI.WebControls.TextBox txtuploadType;
		protected global::System.Web.UI.WebControls.TextBox txtNextFullTime;
		protected global::System.Web.UI.WebControls.TextBox txtNextAddTime;
		protected global::System.Web.UI.WebControls.CheckBox chkUploading;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
