//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.UploadPolicyResult {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblstartMode;
	protected global::System.Web.UI.WebControls.Label lblupload_platFrom;
	protected global::System.Web.UI.WebControls.Label lblupload_class;
	protected global::System.Web.UI.WebControls.Label lbluploadType;
	protected global::System.Web.UI.WebControls.Label lbluploadResult;
	protected global::System.Web.UI.WebControls.Label lbluploadNumber;
	protected global::System.Web.UI.WebControls.Label lblerrorNumber;
	protected global::System.Web.UI.WebControls.Label lblresult;
	protected global::System.Web.UI.WebControls.Label lbluploadTime;
	protected global::System.Web.UI.WebControls.Label lblnoticeTime;
	protected global::System.Web.UI.WebControls.Label lblsys_id;


       
    }
}
