//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.查询 {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblDate;
	protected global::System.Web.UI.WebControls.Label lblFrom_Code;
	protected global::System.Web.UI.WebControls.Label lblTo_Code;
	protected global::System.Web.UI.WebControls.Label lblStartCity;
	protected global::System.Web.UI.WebControls.Label lblArriveCity;
	protected global::System.Web.UI.WebControls.Label lblMileage;
	protected global::System.Web.UI.WebControls.Label lblFule_Adult;
	protected global::System.Web.UI.WebControls.Label lblFule_Child;
	protected global::System.Web.UI.WebControls.Label lblLine_Number;
	protected global::System.Web.UI.WebControls.Label lblShare_Line;
	protected global::System.Web.UI.WebControls.Label lblCompany;
	protected global::System.Web.UI.WebControls.Label lblStartCode;
	protected global::System.Web.UI.WebControls.Label lblStartAirport;
	protected global::System.Web.UI.WebControls.Label lblArriveCode;
	protected global::System.Web.UI.WebControls.Label lblArriveAirport;
	protected global::System.Web.UI.WebControls.Label lblStartTime;
	protected global::System.Web.UI.WebControls.Label lblArriveTime;
	protected global::System.Web.UI.WebControls.Label lblAirRax;
	protected global::System.Web.UI.WebControls.Label lblFuleRax;
	protected global::System.Web.UI.WebControls.Label lblFuelAdu;
	protected global::System.Web.UI.WebControls.Label lblFuelChd;
	protected global::System.Web.UI.WebControls.Label lblFood;
	protected global::System.Web.UI.WebControls.Label lblFood_Detail;
	protected global::System.Web.UI.WebControls.Label lblDirect_Flight;
	protected global::System.Web.UI.WebControls.Label lblType;
	protected global::System.Web.UI.WebControls.Label lblElectronic_Ticket;
	protected global::System.Web.UI.WebControls.Label lblStart_Terminal;
	protected global::System.Web.UI.WebControls.Label lblArrive_Terminal;
	protected global::System.Web.UI.WebControls.Label lblCabin;
	protected global::System.Web.UI.WebControls.Label lblChildCabin;
	protected global::System.Web.UI.WebControls.Label lblDiscount;
	protected global::System.Web.UI.WebControls.Label lblPrice;
	protected global::System.Web.UI.WebControls.Label lblSurplus_Seat_Qty;
	protected global::System.Web.UI.WebControls.Label lblCabin_Status;
	protected global::System.Web.UI.WebControls.Label lblCabin_Point;
	protected global::System.Web.UI.WebControls.Label lblValidity_Period;
	protected global::System.Web.UI.WebControls.Label lblReturn_Date;
	protected global::System.Web.UI.WebControls.Label lblValid_Date;


       
    }
}
