//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.JinRiOrderByPnr {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtorderNo;
		protected global::System.Web.UI.WebControls.TextBox txtpnr;
		protected global::System.Web.UI.WebControls.TextBox txtgrowDiscount;
		protected global::System.Web.UI.WebControls.TextBox txtstayDiscount;
		protected global::System.Web.UI.WebControls.TextBox txtpayMoney;
		protected global::System.Web.UI.WebControls.TextBox txtprofit;
		protected global::System.Web.UI.WebControls.TextBox txtstatus;
		protected global::System.Web.UI.WebControls.TextBox txtdate;
		protected global::System.Web.UI.WebControls.TextBox txtscity;
		protected global::System.Web.UI.WebControls.TextBox txtecity;
		protected global::System.Web.UI.WebControls.TextBox txtflight;
		protected global::System.Web.UI.WebControls.TextBox txtstime;
		protected global::System.Web.UI.WebControls.TextBox txtetime;
		protected global::System.Web.UI.WebControls.TextBox txtcabin;
		protected global::System.Web.UI.WebControls.TextBox txtprice;
		protected global::System.Web.UI.WebControls.TextBox txttax;
		protected global::System.Web.UI.WebControls.TextBox txtpcount;
		protected global::System.Web.UI.WebControls.TextBox txtpName;
		protected global::System.Web.UI.WebControls.TextBox txtpCard;
		protected global::System.Web.UI.WebControls.TextBox txtjouneryInfo;
		protected global::System.Web.UI.WebControls.TextBox txtisBuyInsurance;
		protected global::System.Web.UI.WebControls.TextBox txtorderinfo_id;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
