//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.JinRiOrderByPnr {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblorderNo;
	protected global::System.Web.UI.WebControls.Label lblpnr;
	protected global::System.Web.UI.WebControls.Label lblgrowDiscount;
	protected global::System.Web.UI.WebControls.Label lblstayDiscount;
	protected global::System.Web.UI.WebControls.Label lblpayMoney;
	protected global::System.Web.UI.WebControls.Label lblprofit;
	protected global::System.Web.UI.WebControls.Label lblstatus;
	protected global::System.Web.UI.WebControls.Label lbldate;
	protected global::System.Web.UI.WebControls.Label lblscity;
	protected global::System.Web.UI.WebControls.Label lblecity;
	protected global::System.Web.UI.WebControls.Label lblflight;
	protected global::System.Web.UI.WebControls.Label lblstime;
	protected global::System.Web.UI.WebControls.Label lbletime;
	protected global::System.Web.UI.WebControls.Label lblcabin;
	protected global::System.Web.UI.WebControls.Label lblprice;
	protected global::System.Web.UI.WebControls.Label lbltax;
	protected global::System.Web.UI.WebControls.Label lblpcount;
	protected global::System.Web.UI.WebControls.Label lblpName;
	protected global::System.Web.UI.WebControls.Label lblpCard;
	protected global::System.Web.UI.WebControls.Label lbljouneryInfo;
	protected global::System.Web.UI.WebControls.Label lblisBuyInsurance;
	protected global::System.Web.UI.WebControls.Label lblorderinfo_id;


       
    }
}
