//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.ctripPolicyOptions {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txttolerate_stationary_point;
		protected global::System.Web.UI.WebControls.TextBox txttolerate_leave_money;
		protected global::System.Web.UI.WebControls.TextBox txtlowest_rebate;
		protected global::System.Web.UI.WebControls.TextBox txthighest_rebate;
		protected global::System.Web.UI.WebControls.TextBox txtearliest_advance_days;
		protected global::System.Web.UI.WebControls.TextBox txtnight_before_days;
		protected global::System.Web.UI.WebControls.TextBox txtrebate_class_set;
		protected global::System.Web.UI.WebControls.TextBox txtticket_price_set;
		protected global::System.Web.UI.WebControls.TextBox txtworkTimeLimit;
		protected global::System.Web.UI.WebControls.TextBox txtdiscount;
		protected global::System.Web.UI.WebControls.CheckBox chkis_automatic_ticket;
		protected global::System.Web.UI.WebControls.CheckBox chkis_mail_itinerary;
		protected global::System.Web.UI.WebControls.TextBox txtoff_number;
		protected global::System.Web.UI.WebControls.CheckBox chkis_orientate;
		protected global::System.Web.UI.WebControls.TextBox txtspecial_ticketing_instructions;
		protected global::System.Web.UI.WebControls.TextBox txtrefund_change_rule;
		protected global::System.Web.UI.WebControls.TextBox txtplatform_type_id;
		protected global::System.Web.UI.WebControls.TextBox txtsys_id;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
