//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIRCRM.UI.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.OpenApiSoap")]
    public interface OpenApiSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 xmlData 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlSubmit", ReplyAction="*")]
        AIRCRM.UI.ServiceReference1.XmlSubmitResponse XmlSubmit(AIRCRM.UI.ServiceReference1.XmlSubmitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/XmlSubmit", ReplyAction="*")]
        System.Threading.Tasks.Task<AIRCRM.UI.ServiceReference1.XmlSubmitResponse> XmlSubmitAsync(AIRCRM.UI.ServiceReference1.XmlSubmitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FileSubmit", ReplyAction="*")]
        AIRCRM.UI.ServiceReference1.FileSubmitResponse FileSubmit(AIRCRM.UI.ServiceReference1.FileSubmitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FileSubmit", ReplyAction="*")]
        System.Threading.Tasks.Task<AIRCRM.UI.ServiceReference1.FileSubmitResponse> FileSubmitAsync(AIRCRM.UI.ServiceReference1.FileSubmitRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlSubmitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlSubmit", Namespace="http://tempuri.org/", Order=0)]
        public AIRCRM.UI.ServiceReference1.XmlSubmitRequestBody Body;
        
        public XmlSubmitRequest() {
        }
        
        public XmlSubmitRequest(AIRCRM.UI.ServiceReference1.XmlSubmitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmlSubmitRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlData;
        
        public XmlSubmitRequestBody() {
        }
        
        public XmlSubmitRequestBody(string xmlData) {
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class XmlSubmitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="XmlSubmitResponse", Namespace="http://tempuri.org/", Order=0)]
        public AIRCRM.UI.ServiceReference1.XmlSubmitResponseBody Body;
        
        public XmlSubmitResponse() {
        }
        
        public XmlSubmitResponse(AIRCRM.UI.ServiceReference1.XmlSubmitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class XmlSubmitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XmlSubmitResult;
        
        public XmlSubmitResponseBody() {
        }
        
        public XmlSubmitResponseBody(string XmlSubmitResult) {
            this.XmlSubmitResult = XmlSubmitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FileSubmitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FileSubmit", Namespace="http://tempuri.org/", Order=0)]
        public AIRCRM.UI.ServiceReference1.FileSubmitRequestBody Body;
        
        public FileSubmitRequest() {
        }
        
        public FileSubmitRequest(AIRCRM.UI.ServiceReference1.FileSubmitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FileSubmitRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlData;
        
        public FileSubmitRequestBody() {
        }
        
        public FileSubmitRequestBody(string xmlData) {
            this.xmlData = xmlData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FileSubmitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FileSubmitResponse", Namespace="http://tempuri.org/", Order=0)]
        public AIRCRM.UI.ServiceReference1.FileSubmitResponseBody Body;
        
        public FileSubmitResponse() {
        }
        
        public FileSubmitResponse(AIRCRM.UI.ServiceReference1.FileSubmitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FileSubmitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] FileSubmitResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string error;
        
        public FileSubmitResponseBody() {
        }
        
        public FileSubmitResponseBody(byte[] FileSubmitResult, string error) {
            this.FileSubmitResult = FileSubmitResult;
            this.error = error;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OpenApiSoapChannel : AIRCRM.UI.ServiceReference1.OpenApiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OpenApiSoapClient : System.ServiceModel.ClientBase<AIRCRM.UI.ServiceReference1.OpenApiSoap>, AIRCRM.UI.ServiceReference1.OpenApiSoap {
        
        public OpenApiSoapClient() {
        }
        
        public OpenApiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OpenApiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OpenApiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OpenApiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AIRCRM.UI.ServiceReference1.XmlSubmitResponse AIRCRM.UI.ServiceReference1.OpenApiSoap.XmlSubmit(AIRCRM.UI.ServiceReference1.XmlSubmitRequest request) {
            return base.Channel.XmlSubmit(request);
        }
        
        public string XmlSubmit(string xmlData) {
            AIRCRM.UI.ServiceReference1.XmlSubmitRequest inValue = new AIRCRM.UI.ServiceReference1.XmlSubmitRequest();
            inValue.Body = new AIRCRM.UI.ServiceReference1.XmlSubmitRequestBody();
            inValue.Body.xmlData = xmlData;
            AIRCRM.UI.ServiceReference1.XmlSubmitResponse retVal = ((AIRCRM.UI.ServiceReference1.OpenApiSoap)(this)).XmlSubmit(inValue);
            return retVal.Body.XmlSubmitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AIRCRM.UI.ServiceReference1.XmlSubmitResponse> AIRCRM.UI.ServiceReference1.OpenApiSoap.XmlSubmitAsync(AIRCRM.UI.ServiceReference1.XmlSubmitRequest request) {
            return base.Channel.XmlSubmitAsync(request);
        }
        
        public System.Threading.Tasks.Task<AIRCRM.UI.ServiceReference1.XmlSubmitResponse> XmlSubmitAsync(string xmlData) {
            AIRCRM.UI.ServiceReference1.XmlSubmitRequest inValue = new AIRCRM.UI.ServiceReference1.XmlSubmitRequest();
            inValue.Body = new AIRCRM.UI.ServiceReference1.XmlSubmitRequestBody();
            inValue.Body.xmlData = xmlData;
            return ((AIRCRM.UI.ServiceReference1.OpenApiSoap)(this)).XmlSubmitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AIRCRM.UI.ServiceReference1.FileSubmitResponse AIRCRM.UI.ServiceReference1.OpenApiSoap.FileSubmit(AIRCRM.UI.ServiceReference1.FileSubmitRequest request) {
            return base.Channel.FileSubmit(request);
        }
        
        public byte[] FileSubmit(string xmlData, out string error) {
            AIRCRM.UI.ServiceReference1.FileSubmitRequest inValue = new AIRCRM.UI.ServiceReference1.FileSubmitRequest();
            inValue.Body = new AIRCRM.UI.ServiceReference1.FileSubmitRequestBody();
            inValue.Body.xmlData = xmlData;
            AIRCRM.UI.ServiceReference1.FileSubmitResponse retVal = ((AIRCRM.UI.ServiceReference1.OpenApiSoap)(this)).FileSubmit(inValue);
            error = retVal.Body.error;
            return retVal.Body.FileSubmitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AIRCRM.UI.ServiceReference1.FileSubmitResponse> AIRCRM.UI.ServiceReference1.OpenApiSoap.FileSubmitAsync(AIRCRM.UI.ServiceReference1.FileSubmitRequest request) {
            return base.Channel.FileSubmitAsync(request);
        }
        
        public System.Threading.Tasks.Task<AIRCRM.UI.ServiceReference1.FileSubmitResponse> FileSubmitAsync(string xmlData) {
            AIRCRM.UI.ServiceReference1.FileSubmitRequest inValue = new AIRCRM.UI.ServiceReference1.FileSubmitRequest();
            inValue.Body = new AIRCRM.UI.ServiceReference1.FileSubmitRequestBody();
            inValue.Body.xmlData = xmlData;
            return ((AIRCRM.UI.ServiceReference1.OpenApiSoap)(this)).FileSubmitAsync(inValue);
        }
    }
}
