//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.PurchaseOrderInfo {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtprice;
		protected global::System.Web.UI.WebControls.TextBox txtissue_ticket_type;
		protected global::System.Web.UI.WebControls.TextBox txtissue_ticket_platform_code;
		protected global::System.Web.UI.WebControls.TextBox txtsource_transaction_id;
		protected global::System.Web.UI.WebControls.TextBox txtsource_order_no;
		protected global::System.Web.UI.WebControls.TextBox txttpp_type;
		protected global::System.Web.UI.WebControls.TextBox txtstatus;
		protected global::System.Web.UI.WebControls.TextBox txtpay_commercial_no;
		protected global::System.Web.UI.WebControls.TextBox txtoffline_pay_type;
		protected global::System.Web.UI.WebControls.TextBox txtoffline_pay_cardno;
		protected global::System.Web.UI.WebControls.TextBox txtplatform_mem_id;
		protected global::System.Web.UI.WebControls.TextBox txtoperator;
		protected global::System.Web.UI.WebControls.TextBox txtrefund_price;
		protected global::System.Web.UI.WebControls.TextBox txto_id;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
