//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.PurchaseOrderInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblprice;
	protected global::System.Web.UI.WebControls.Label lblissue_ticket_type;
	protected global::System.Web.UI.WebControls.Label lblissue_ticket_platform_code;
	protected global::System.Web.UI.WebControls.Label lblsource_transaction_id;
	protected global::System.Web.UI.WebControls.Label lblsource_order_no;
	protected global::System.Web.UI.WebControls.Label lbltpp_type;
	protected global::System.Web.UI.WebControls.Label lblstatus;
	protected global::System.Web.UI.WebControls.Label lblpay_commercial_no;
	protected global::System.Web.UI.WebControls.Label lbloffline_pay_type;
	protected global::System.Web.UI.WebControls.Label lbloffline_pay_cardno;
	protected global::System.Web.UI.WebControls.Label lblplatform_mem_id;
	protected global::System.Web.UI.WebControls.Label lbloperator;
	protected global::System.Web.UI.WebControls.Label lblrefund_price;
	protected global::System.Web.UI.WebControls.Label lblo_id;


       
    }
}
