//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.Passenger {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtname;
		protected global::System.Web.UI.WebControls.TextBox txtageType;
		protected global::System.Web.UI.WebControls.TextBox txtcardType;
		protected global::System.Web.UI.WebControls.TextBox txtprice;
		protected global::System.Web.UI.WebControls.TextBox txtpriceType;
		protected global::System.Web.UI.WebControls.TextBox txtcardNum;
		protected global::System.Web.UI.WebControls.TextBox txteticketNum;
		protected global::System.Web.UI.WebControls.TextBox txtinsuranceCount;
		protected global::System.Web.UI.WebControls.TextBox txtbxSource;
		protected global::System.Web.UI.WebControls.TextBox txtbxName;
		protected global::System.Web.UI.WebControls.TextBox txto_id;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
