//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.DeletePolicy {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtflightcode;
		protected global::System.Web.UI.WebControls.TextBox txtpolicyCode;
		protected global::System.Web.UI.WebControls.TextBox txtdpt;
		protected global::System.Web.UI.WebControls.TextBox txtarr;
		protected global::System.Web.UI.WebControls.TextBox txtcabin;
		protected global::System.Web.UI.WebControls.TextBox txtstartdate;
		protected global::System.Web.UI.WebControls.TextBox txtenddate;
		protected global::System.Web.UI.WebControls.TextBox txtsys_id;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
