//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policy
{
    using System;
    using System.Collections.Generic;
    
    public partial class API380Ticket
    {
        public int id { get; set; }
        public int code { get; set; }
        public string message { get; set; }
        public string bigpnr { get; set; }
        public string air { get; set; }
        public string pnr { get; set; }
        public string paystatus { get; set; }
        public string totaltax { get; set; }
        public string ticketprice { get; set; }
        public string orderno { get; set; }
        public int platformB2B_name_id { get; set; }
    }
}
