//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policy
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaQianYiPolicy
    {
        public int ID { get; set; }
        public string policy_num { get; set; }
        public string startcity { get; set; }
        public string arrivecity { get; set; }
        public string airline { get; set; }
        public string for_flight_no { get; set; }
        public string ex_flight_no { get; set; }
        public string policy_ratype { get; set; }
        public string point { get; set; }
        public string cabin_discount { get; set; }
        public string startdate { get; set; }
        public string arrivedate { get; set; }
        public string nomal_workday { get; set; }
        public string weekday { get; set; }
        public string vip_policy { get; set; }
        public string return_policy { get; set; }
        public string policy_type { get; set; }
        public string policy_note { get; set; }
        public string supplier_id { get; set; }
        public string or_ticket_t { get; set; }
        public string week_ticket_t { get; set; }
        public string policy_flight { get; set; }
        public string end_state { get; set; }
        public string office_code { get; set; }
        public string salestart_date { get; set; }
        public string saleend_date { get; set; }
        public string support_pay { get; set; }
        public string ticket_efficient { get; set; }
        public string is_cgnum_ticket { get; set; }
        public string is_open_low { get; set; }
        public string addtime { get; set; }
        public string last_modify_time { get; set; }
        public Nullable<bool> IsUpload { get; set; }
        public Nullable<bool> IsUpdate { get; set; }
    }
}
