//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policy
{
    using System;
    using System.Collections.Generic;
    
    public partial class C517NaBenefit
    {
        public int ID { get; set; }
        public string PolicyNum { get; set; }
        public string Airline { get; set; }
        public string Scity { get; set; }
        public string Acity { get; set; }
        public string AirType { get; set; }
        public string Flight { get; set; }
        public string Cabin { get; set; }
        public string TripType { get; set; }
        public string PolicyType { get; set; }
        public string PolicyPoint { get; set; }
        public string ScheduleRestr { get; set; }
        public string TicketCondition { get; set; }
        public string AvaDate { get; set; }
        public string EndDate { get; set; }
        public string SupplierTimeDay { get; set; }
        public string SupplierTimeWeek { get; set; }
        public string IsSpeciPolicy { get; set; }
        public string IsChange { get; set; }
        public string ChildPolicyNum { get; set; }
        public string PayPrice { get; set; }
        public string Ticket { get; set; }
        public string Airrax { get; set; }
        public string Fuel { get; set; }
        public string SupplierDelDay { get; set; }
        public string SupplierDelWeek { get; set; }
        public string TicketEffic { get; set; }
        public string UpgradeChange { get; set; }
        public string OfficeCode { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<bool> IsUpload { get; set; }
        public Nullable<bool> IsUpdate { get; set; }
    }
}
