//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policy
{
    using System;
    using System.Collections.Generic;
    
    public partial class C51bookPolicy
    {
        public int ID { get; set; }
        public string adultAirportTax { get; set; }
        public string adultFuelTax { get; set; }
        public string childAirportTax { get; set; }
        public string childFuelTax { get; set; }
        public string flightNo { get; set; }
        public string adultSettlePrice { get; set; }
        public string airlineCode { get; set; }
        public string comment { get; set; }
        public string commisionPoint { get; set; }
        public string needSwitchPNR { get; set; }
        public string policyId { get; set; }
        public string policyType { get; set; }
        public string productType { get; set; }
        public string routeType { get; set; }
        public string seatType { get; set; }
        public string supplyOfficeNo { get; set; }
        public string ticketSpeed { get; set; }
        public string vtWorkTime { get; set; }
        public string workTime { get; set; }
        public string seatCode { get; set; }
        public string ticketPrice { get; set; }
        public Nullable<System.DateTime> Addtime { get; set; }
        public Nullable<bool> IsUpload { get; set; }
        public Nullable<bool> IsUpdate { get; set; }
    }
}
