//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Policy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket380Policy
    {
        public int ID { get; set; }
        public string policy_id { get; set; }
        public string air_comp { get; set; }
        public string start_city { get; set; }
        public string arr_city { get; set; }
        public string flight { get; set; }
        public string cabin { get; set; }
        public string share_line { get; set; }
        public string cabinprice { get; set; }
        public string point { get; set; }
        public string nakednum { get; set; }
        public string is_auto_tic { get; set; }
        public string logtime { get; set; }
        public string deptime { get; set; }
        public string price { get; set; }
        public string remark { get; set; }
        public string fsdate { get; set; }
        public string fedate { get; set; }
        public string sale_sdate { get; set; }
        public string sale_edate { get; set; }
        public string AddTime { get; set; }
        public Nullable<bool> IsUpload { get; set; }
        public Nullable<bool> IsUpdate { get; set; }
    }
}
