//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.sysAdminUser {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblusername;
	protected global::System.Web.UI.WebControls.Label lblpassword;
	protected global::System.Web.UI.WebControls.Label lblCreateDate;
	protected global::System.Web.UI.WebControls.Label lblRoleList;
	protected global::System.Web.UI.WebControls.Label lblCheckAuthority;
	protected global::System.Web.UI.WebControls.Label lblStop;
	protected global::System.Web.UI.WebControls.Label lblIsMoify;
	protected global::System.Web.UI.WebControls.Label lblRemark;
	protected global::System.Web.UI.WebControls.Label lblRealName;
	protected global::System.Web.UI.WebControls.Label lblCode;
	protected global::System.Web.UI.WebControls.Label lblMobile;
	protected global::System.Web.UI.WebControls.Label lblTelephone;
	protected global::System.Web.UI.WebControls.Label lblQQ;
	protected global::System.Web.UI.WebControls.Label lblEmaile;
	protected global::System.Web.UI.WebControls.Label lblCompany;
	protected global::System.Web.UI.WebControls.Label lblCompanyAddress;
	protected global::System.Web.UI.WebControls.Label lblParentID;


       
    }
}
