//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.51bookPolicy {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtadultAirportTax;
		protected global::System.Web.UI.WebControls.TextBox txtadultFuelTax;
		protected global::System.Web.UI.WebControls.TextBox txtchildAirportTax;
		protected global::System.Web.UI.WebControls.TextBox txtchildFuelTax;
		protected global::System.Web.UI.WebControls.TextBox txtflightNo;
		protected global::System.Web.UI.WebControls.TextBox txtadultSettlePrice;
		protected global::System.Web.UI.WebControls.TextBox txtairlineCode;
		protected global::System.Web.UI.WebControls.TextBox txtcomment;
		protected global::System.Web.UI.WebControls.TextBox txtcommisionPoint;
		protected global::System.Web.UI.WebControls.TextBox txtneedSwitchPNR;
		protected global::System.Web.UI.WebControls.TextBox txtpolicyId;
		protected global::System.Web.UI.WebControls.TextBox txtpolicyType;
		protected global::System.Web.UI.WebControls.TextBox txtproductType;
		protected global::System.Web.UI.WebControls.TextBox txtrouteType;
		protected global::System.Web.UI.WebControls.TextBox txtseatType;
		protected global::System.Web.UI.WebControls.TextBox txtsupplyOfficeNo;
		protected global::System.Web.UI.WebControls.TextBox txtticketSpeed;
		protected global::System.Web.UI.WebControls.TextBox txtvtWorkTime;
		protected global::System.Web.UI.WebControls.TextBox txtworkTime;
		protected global::System.Web.UI.WebControls.TextBox txtseatCode;
		protected global::System.Web.UI.WebControls.TextBox txtticketPrice;
		protected global::System.Web.UI.WebControls.TextBox txtAddtime;
		protected global::System.Web.UI.WebControls.CheckBox chkIsUpload;
		protected global::System.Web.UI.WebControls.CheckBox chkIsUpdate;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
