//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.51bookPolicy {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lbladultAirportTax;
	protected global::System.Web.UI.WebControls.Label lbladultFuelTax;
	protected global::System.Web.UI.WebControls.Label lblchildAirportTax;
	protected global::System.Web.UI.WebControls.Label lblchildFuelTax;
	protected global::System.Web.UI.WebControls.Label lblflightNo;
	protected global::System.Web.UI.WebControls.Label lbladultSettlePrice;
	protected global::System.Web.UI.WebControls.Label lblairlineCode;
	protected global::System.Web.UI.WebControls.Label lblcomment;
	protected global::System.Web.UI.WebControls.Label lblcommisionPoint;
	protected global::System.Web.UI.WebControls.Label lblneedSwitchPNR;
	protected global::System.Web.UI.WebControls.Label lblpolicyId;
	protected global::System.Web.UI.WebControls.Label lblpolicyType;
	protected global::System.Web.UI.WebControls.Label lblproductType;
	protected global::System.Web.UI.WebControls.Label lblrouteType;
	protected global::System.Web.UI.WebControls.Label lblseatType;
	protected global::System.Web.UI.WebControls.Label lblsupplyOfficeNo;
	protected global::System.Web.UI.WebControls.Label lblticketSpeed;
	protected global::System.Web.UI.WebControls.Label lblvtWorkTime;
	protected global::System.Web.UI.WebControls.Label lblworkTime;
	protected global::System.Web.UI.WebControls.Label lblseatCode;
	protected global::System.Web.UI.WebControls.Label lblticketPrice;
	protected global::System.Web.UI.WebControls.Label lblAddtime;
	protected global::System.Web.UI.WebControls.Label lblIsUpload;
	protected global::System.Web.UI.WebControls.Label lblIsUpdate;


       
    }
}
