//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.ctripPolicyRebate {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtnavigation_company;
		protected global::System.Web.UI.WebControls.TextBox txtair_line;
		protected global::System.Web.UI.WebControls.TextBox txtapplication_space;
		protected global::System.Web.UI.WebControls.TextBox txtrabate_number;
		protected global::System.Web.UI.WebControls.TextBox txtleave_money;
		protected global::System.Web.UI.WebControls.TextBox txtticket_price_lowest;
		protected global::System.Web.UI.WebControls.TextBox txtticket_price_highest;
		protected global::System.Web.UI.WebControls.TextBox txtrabate_class;
		protected global::System.Web.UI.WebControls.TextBox txtreturnType;
		protected global::System.Web.UI.WebControls.TextBox txtsys_id;
		protected global::System.Web.UI.WebControls.TextBox txtplatform_type_id;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
