//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.517NaBenefit {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtID;
		protected global::System.Web.UI.WebControls.TextBox txtPolicyNum;
		protected global::System.Web.UI.WebControls.TextBox txtAirline;
		protected global::System.Web.UI.WebControls.TextBox txtScity;
		protected global::System.Web.UI.WebControls.TextBox txtAcity;
		protected global::System.Web.UI.WebControls.TextBox txtAirType;
		protected global::System.Web.UI.WebControls.TextBox txtFlight;
		protected global::System.Web.UI.WebControls.TextBox txtCabin;
		protected global::System.Web.UI.WebControls.TextBox txtTripType;
		protected global::System.Web.UI.WebControls.TextBox txtPolicyType;
		protected global::System.Web.UI.WebControls.TextBox txtPolicyPoint;
		protected global::System.Web.UI.WebControls.TextBox txtScheduleRestr;
		protected global::System.Web.UI.WebControls.TextBox txtTicketCondition;
		protected global::System.Web.UI.WebControls.TextBox txtAvaDate;
		protected global::System.Web.UI.WebControls.TextBox txtEndDate;
		protected global::System.Web.UI.WebControls.TextBox txtSupplierTimeDay;
		protected global::System.Web.UI.WebControls.TextBox txtSupplierTimeWeek;
		protected global::System.Web.UI.WebControls.TextBox txtIsSpeciPolicy;
		protected global::System.Web.UI.WebControls.TextBox txtIsChange;
		protected global::System.Web.UI.WebControls.TextBox txtChildPolicyNum;
		protected global::System.Web.UI.WebControls.TextBox txtPayPrice;
		protected global::System.Web.UI.WebControls.TextBox txtTicket;
		protected global::System.Web.UI.WebControls.TextBox txtAirrax;
		protected global::System.Web.UI.WebControls.TextBox txtFuel;
		protected global::System.Web.UI.WebControls.TextBox txtSupplierDelDay;
		protected global::System.Web.UI.WebControls.TextBox txtSupplierDelWeek;
		protected global::System.Web.UI.WebControls.TextBox txtTicketEffic;
		protected global::System.Web.UI.WebControls.TextBox txtUpgradeChange;
		protected global::System.Web.UI.WebControls.TextBox txtOfficeCode;
		protected global::System.Web.UI.WebControls.TextBox txtAddTime;
		protected global::System.Web.UI.WebControls.CheckBox chkIsUpload;
		protected global::System.Web.UI.WebControls.CheckBox chkIsUpdate;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
