//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.517NaBenefit {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblPolicyNum;
	protected global::System.Web.UI.WebControls.Label lblAirline;
	protected global::System.Web.UI.WebControls.Label lblScity;
	protected global::System.Web.UI.WebControls.Label lblAcity;
	protected global::System.Web.UI.WebControls.Label lblAirType;
	protected global::System.Web.UI.WebControls.Label lblFlight;
	protected global::System.Web.UI.WebControls.Label lblCabin;
	protected global::System.Web.UI.WebControls.Label lblTripType;
	protected global::System.Web.UI.WebControls.Label lblPolicyType;
	protected global::System.Web.UI.WebControls.Label lblPolicyPoint;
	protected global::System.Web.UI.WebControls.Label lblScheduleRestr;
	protected global::System.Web.UI.WebControls.Label lblTicketCondition;
	protected global::System.Web.UI.WebControls.Label lblAvaDate;
	protected global::System.Web.UI.WebControls.Label lblEndDate;
	protected global::System.Web.UI.WebControls.Label lblSupplierTimeDay;
	protected global::System.Web.UI.WebControls.Label lblSupplierTimeWeek;
	protected global::System.Web.UI.WebControls.Label lblIsSpeciPolicy;
	protected global::System.Web.UI.WebControls.Label lblIsChange;
	protected global::System.Web.UI.WebControls.Label lblChildPolicyNum;
	protected global::System.Web.UI.WebControls.Label lblPayPrice;
	protected global::System.Web.UI.WebControls.Label lblTicket;
	protected global::System.Web.UI.WebControls.Label lblAirrax;
	protected global::System.Web.UI.WebControls.Label lblFuel;
	protected global::System.Web.UI.WebControls.Label lblSupplierDelDay;
	protected global::System.Web.UI.WebControls.Label lblSupplierDelWeek;
	protected global::System.Web.UI.WebControls.Label lblTicketEffic;
	protected global::System.Web.UI.WebControls.Label lblUpgradeChange;
	protected global::System.Web.UI.WebControls.Label lblOfficeCode;
	protected global::System.Web.UI.WebControls.Label lblAddTime;
	protected global::System.Web.UI.WebControls.Label lblIsUpload;
	protected global::System.Web.UI.WebControls.Label lblIsUpdate;


       
    }
}
