//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.Jinri_Order_Response {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtOrderNo;
		protected global::System.Web.UI.WebControls.TextBox txtPNR;
		protected global::System.Web.UI.WebControls.TextBox txtGrowDiscount;
		protected global::System.Web.UI.WebControls.TextBox txtStayDiscount;
		protected global::System.Web.UI.WebControls.TextBox txtPayMoney;
		protected global::System.Web.UI.WebControls.TextBox txtProfit;
		protected global::System.Web.UI.WebControls.TextBox txtStatus;
		protected global::System.Web.UI.WebControls.TextBox txtDate;
		protected global::System.Web.UI.WebControls.TextBox txtScity;
		protected global::System.Web.UI.WebControls.TextBox txtEcity;
		protected global::System.Web.UI.WebControls.TextBox txtFlight;
		protected global::System.Web.UI.WebControls.TextBox txtStime;
		protected global::System.Web.UI.WebControls.TextBox txtEtime;
		protected global::System.Web.UI.WebControls.TextBox txtCabin;
		protected global::System.Web.UI.WebControls.TextBox txtPrice;
		protected global::System.Web.UI.WebControls.TextBox txtTax;
		protected global::System.Web.UI.WebControls.TextBox txtPCount;
		protected global::System.Web.UI.WebControls.TextBox txtPName;
		protected global::System.Web.UI.WebControls.TextBox txtPCard;
		protected global::System.Web.UI.WebControls.TextBox txtJouneryInfo;
		protected global::System.Web.UI.WebControls.TextBox txtIsBuyInsurance;
		protected global::System.Web.UI.WebControls.TextBox txtremark;
		protected global::System.Web.UI.WebControls.TextBox txtticket_no;
		protected global::System.Web.UI.WebControls.TextBox txtrefund_type;
		protected global::System.Web.UI.WebControls.TextBox txtamount;
		protected global::System.Web.UI.WebControls.TextBox txtpay_type;
		protected global::System.Web.UI.WebControls.TextBox txttrade_no;
		protected global::System.Web.UI.WebControls.TextBox txtpay_time;
		protected global::System.Web.UI.WebControls.TextBox txtOrderInfo_id;
		protected global::System.Web.UI.WebControls.TextBox txtplatformB2B_name_id;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
