//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.Jinri_Order_Response {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblOrderNo;
	protected global::System.Web.UI.WebControls.Label lblPNR;
	protected global::System.Web.UI.WebControls.Label lblGrowDiscount;
	protected global::System.Web.UI.WebControls.Label lblStayDiscount;
	protected global::System.Web.UI.WebControls.Label lblPayMoney;
	protected global::System.Web.UI.WebControls.Label lblProfit;
	protected global::System.Web.UI.WebControls.Label lblStatus;
	protected global::System.Web.UI.WebControls.Label lblDate;
	protected global::System.Web.UI.WebControls.Label lblScity;
	protected global::System.Web.UI.WebControls.Label lblEcity;
	protected global::System.Web.UI.WebControls.Label lblFlight;
	protected global::System.Web.UI.WebControls.Label lblStime;
	protected global::System.Web.UI.WebControls.Label lblEtime;
	protected global::System.Web.UI.WebControls.Label lblCabin;
	protected global::System.Web.UI.WebControls.Label lblPrice;
	protected global::System.Web.UI.WebControls.Label lblTax;
	protected global::System.Web.UI.WebControls.Label lblPCount;
	protected global::System.Web.UI.WebControls.Label lblPName;
	protected global::System.Web.UI.WebControls.Label lblPCard;
	protected global::System.Web.UI.WebControls.Label lblJouneryInfo;
	protected global::System.Web.UI.WebControls.Label lblIsBuyInsurance;
	protected global::System.Web.UI.WebControls.Label lblremark;
	protected global::System.Web.UI.WebControls.Label lblticket_no;
	protected global::System.Web.UI.WebControls.Label lblrefund_type;
	protected global::System.Web.UI.WebControls.Label lblamount;
	protected global::System.Web.UI.WebControls.Label lblpay_type;
	protected global::System.Web.UI.WebControls.Label lbltrade_no;
	protected global::System.Web.UI.WebControls.Label lblpay_time;
	protected global::System.Web.UI.WebControls.Label lblOrderInfo_id;
	protected global::System.Web.UI.WebControls.Label lblplatformB2B_name_id;


       
    }
}
