//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.OrderInfo2 {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblpk_id;
		protected global::System.Web.UI.WebControls.TextBox txtid;
	protected global::System.Web.UI.WebControls.Label lblorderNo;
		protected global::System.Web.UI.WebControls.TextBox txtallPrice;
		protected global::System.Web.UI.WebControls.TextBox txtnoPay;
		protected global::System.Web.UI.WebControls.TextBox txtchildPrintPrice;
		protected global::System.Web.UI.WebControls.TextBox txtchildFaceValue;
		protected global::System.Web.UI.WebControls.TextBox txtsource;
		protected global::System.Web.UI.WebControls.TextBox txtpolicySource;
		protected global::System.Web.UI.WebControls.TextBox txtticketMode;
		protected global::System.Web.UI.WebControls.TextBox txtpolicyFriendly;
		protected global::System.Web.UI.WebControls.TextBox txtpayChannel;
		protected global::System.Web.UI.WebControls.TextBox txtpayStatus;
		protected global::System.Web.UI.WebControls.TextBox txtinsuranceUnitPrice;
		protected global::System.Web.UI.WebControls.TextBox txtbacknote;
		protected global::System.Web.UI.WebControls.TextBox txtinsuranceCuttingPrice;
		protected global::System.Web.UI.WebControls.TextBox txtcabinnote;
		protected global::System.Web.UI.WebControls.TextBox txtxcdPrice;
		protected global::System.Web.UI.WebControls.TextBox txtxcd;
		protected global::System.Web.UI.WebControls.TextBox txtsjr;
		protected global::System.Web.UI.WebControls.TextBox txtcontactTel;
		protected global::System.Web.UI.WebControls.TextBox txtaddress;
		protected global::System.Web.UI.WebControls.TextBox txtcompany;
		protected global::System.Web.UI.WebControls.TextBox txtexpType;
		protected global::System.Web.UI.WebControls.TextBox txtordernumber;
		protected global::System.Web.UI.WebControls.TextBox txtsendtime;
		protected global::System.Web.UI.WebControls.TextBox txtviewPrice;
		protected global::System.Web.UI.WebControls.TextBox txtprice;
		protected global::System.Web.UI.WebControls.TextBox txtpnr;
		protected global::System.Web.UI.WebControls.TextBox txtcpnr;
		protected global::System.Web.UI.WebControls.TextBox txtpnrText;
		protected global::System.Web.UI.WebControls.TextBox txtchildPnrText;
		protected global::System.Web.UI.WebControls.TextBox txtpataText;
		protected global::System.Web.UI.WebControls.TextBox txtchildPataText;
		protected global::System.Web.UI.WebControls.TextBox txtconstructionFee;
		protected global::System.Web.UI.WebControls.TextBox txtfuelTax;
		protected global::System.Web.UI.WebControls.TextBox txtchildFuelTax;
		protected global::System.Web.UI.WebControls.TextBox txtpolicyType;
		protected global::System.Web.UI.WebControls.TextBox txtstatus;
		protected global::System.Web.UI.WebControls.TextBox txtcontact;
		protected global::System.Web.UI.WebControls.TextBox txtcontactMob;
		protected global::System.Web.UI.WebControls.TextBox txtcontactEmail;
		protected global::System.Web.UI.WebControls.TextBox txtcreateTime;
		protected global::System.Web.UI.WebControls.TextBox txtneedPS;
		protected global::System.Web.UI.WebControls.TextBox txtusername;
		protected global::System.Web.UI.WebControls.TextBox txtorderFrom;
		protected global::System.Web.UI.WebControls.TextBox txtlockStatus;
		protected global::System.Web.UI.WebControls.TextBox txtupdateTime;
		protected global::System.Web.UI.WebControls.TextBox txtuserid;
		protected global::System.Web.UI.WebControls.TextBox txtorderDesc;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
