//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.OrderInfo2 {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblpk_id;
	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblorderNo;
	protected global::System.Web.UI.WebControls.Label lblallPrice;
	protected global::System.Web.UI.WebControls.Label lblnoPay;
	protected global::System.Web.UI.WebControls.Label lblchildPrintPrice;
	protected global::System.Web.UI.WebControls.Label lblchildFaceValue;
	protected global::System.Web.UI.WebControls.Label lblsource;
	protected global::System.Web.UI.WebControls.Label lblpolicySource;
	protected global::System.Web.UI.WebControls.Label lblticketMode;
	protected global::System.Web.UI.WebControls.Label lblpolicyFriendly;
	protected global::System.Web.UI.WebControls.Label lblpayChannel;
	protected global::System.Web.UI.WebControls.Label lblpayStatus;
	protected global::System.Web.UI.WebControls.Label lblinsuranceUnitPrice;
	protected global::System.Web.UI.WebControls.Label lblbacknote;
	protected global::System.Web.UI.WebControls.Label lblinsuranceCuttingPrice;
	protected global::System.Web.UI.WebControls.Label lblcabinnote;
	protected global::System.Web.UI.WebControls.Label lblxcdPrice;
	protected global::System.Web.UI.WebControls.Label lblxcd;
	protected global::System.Web.UI.WebControls.Label lblsjr;
	protected global::System.Web.UI.WebControls.Label lblcontactTel;
	protected global::System.Web.UI.WebControls.Label lbladdress;
	protected global::System.Web.UI.WebControls.Label lblcompany;
	protected global::System.Web.UI.WebControls.Label lblexpType;
	protected global::System.Web.UI.WebControls.Label lblordernumber;
	protected global::System.Web.UI.WebControls.Label lblsendtime;
	protected global::System.Web.UI.WebControls.Label lblviewPrice;
	protected global::System.Web.UI.WebControls.Label lblprice;
	protected global::System.Web.UI.WebControls.Label lblpnr;
	protected global::System.Web.UI.WebControls.Label lblcpnr;
	protected global::System.Web.UI.WebControls.Label lblpnrText;
	protected global::System.Web.UI.WebControls.Label lblchildPnrText;
	protected global::System.Web.UI.WebControls.Label lblpataText;
	protected global::System.Web.UI.WebControls.Label lblchildPataText;
	protected global::System.Web.UI.WebControls.Label lblconstructionFee;
	protected global::System.Web.UI.WebControls.Label lblfuelTax;
	protected global::System.Web.UI.WebControls.Label lblchildFuelTax;
	protected global::System.Web.UI.WebControls.Label lblpolicyType;
	protected global::System.Web.UI.WebControls.Label lblstatus;
	protected global::System.Web.UI.WebControls.Label lblcontact;
	protected global::System.Web.UI.WebControls.Label lblcontactMob;
	protected global::System.Web.UI.WebControls.Label lblcontactEmail;
	protected global::System.Web.UI.WebControls.Label lblcreateTime;
	protected global::System.Web.UI.WebControls.Label lblneedPS;
	protected global::System.Web.UI.WebControls.Label lblusername;
	protected global::System.Web.UI.WebControls.Label lblorderFrom;
	protected global::System.Web.UI.WebControls.Label lbllockStatus;
	protected global::System.Web.UI.WebControls.Label lblupdateTime;
	protected global::System.Web.UI.WebControls.Label lbluserid;
	protected global::System.Web.UI.WebControls.Label lblorderDesc;


       
    }
}
