//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.rebate_wangfan {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblnavigation_company;
	protected global::System.Web.UI.WebControls.Label lblair_line;
	protected global::System.Web.UI.WebControls.Label lblqucheng_space;
	protected global::System.Web.UI.WebControls.Label lblhuicheng_space;
	protected global::System.Web.UI.WebControls.Label lblrabate_number;
	protected global::System.Web.UI.WebControls.Label lblleave_money;
	protected global::System.Web.UI.WebControls.Label lblticket_price_lowest;
	protected global::System.Web.UI.WebControls.Label lblticket_price_highest;
	protected global::System.Web.UI.WebControls.Label lblrabate_class;
	protected global::System.Web.UI.WebControls.Label lblsys_id;
	protected global::System.Web.UI.WebControls.Label lblplatform_type_id;


       
    }
}
