//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.policy_zy_pat {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblnavigation_company;
	protected global::System.Web.UI.WebControls.Label lblair_line;
	protected global::System.Web.UI.WebControls.Label lblapplication_space;
	protected global::System.Web.UI.WebControls.Label lblpatCheck;
	protected global::System.Web.UI.WebControls.Label lblplatform_id;
	protected global::System.Web.UI.WebControls.Label lblsys_id;


       
    }
}
