//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.policy_options_wangfan {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lbltolerate_stationary_point;
	protected global::System.Web.UI.WebControls.Label lbltolerate_leave_money;
	protected global::System.Web.UI.WebControls.Label lbllowest_rebate;
	protected global::System.Web.UI.WebControls.Label lblhighest_rebate;
	protected global::System.Web.UI.WebControls.Label lblearliest_advance_days;
	protected global::System.Web.UI.WebControls.Label lblnight_before_days;
	protected global::System.Web.UI.WebControls.Label lblrebate_class_set;
	protected global::System.Web.UI.WebControls.Label lblFlight_departure_time_start;
	protected global::System.Web.UI.WebControls.Label lblFlight_departure_time_end;
	protected global::System.Web.UI.WebControls.Label lblis_automatic_ticket;
	protected global::System.Web.UI.WebControls.Label lblis_mail_itinerary;
	protected global::System.Web.UI.WebControls.Label lblempower_office_number;
	protected global::System.Web.UI.WebControls.Label lbltolerate_refund_change_rule;
	protected global::System.Web.UI.WebControls.Label lblclass_description;
	protected global::System.Web.UI.WebControls.Label lblspecial_ticketing_instructions;
	protected global::System.Web.UI.WebControls.Label lblPolicy_interface_id;
	protected global::System.Web.UI.WebControls.Label lblsys_userId;


       
    }
}
