//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanben.Web.menu {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblicon;
	protected global::System.Web.UI.WebControls.Label lblmenuname;
	protected global::System.Web.UI.WebControls.Label lblurl;
	protected global::System.Web.UI.WebControls.Label lblparentId;
	protected global::System.Web.UI.WebControls.Label lblsort;
	protected global::System.Web.UI.WebControls.Label lblremark;
	protected global::System.Web.UI.WebControls.Label lblstop;


       
    }
}
